(function(jscl){
'use strict';
(function(values, internals){
var l1=internals.intern('TRUE');
var l2=internals.intern('FAIL');
var l3=internals.intern('NOP');
var l4=internals.intern('NIL','COMMON-LISP');
var l5=internals.QIList(l1,l2,l3,l4);
var l6=internals.intern('EXPORT','COMMON-LISP');
l6.fvalue(internals.pv,l5);
var l7=internals.intern('T','COMMON-LISP');
l1.fvalue=(function(){var FUNC=(function JSCL_USER_TRUE(values){var v1=l4.value;
var I;
for (I=arguments.length-1-1;I>=0;I--)v1=new internals.Cons(arguments[I+1],v1);
var v2=this;
return (function(){return l7.value;
})();
});
FUNC.fname='TRUE';
return FUNC;
})();
l1;
l2.value=l4.value;
l2;
l2.fvalue=(function(){var FUNC=(function JSCL_USER_FAIL(values){var v4=l4.value;
var I;
for (I=arguments.length-1-1;I>=0;I--)v4=new internals.Cons(arguments[I+1],v4);
var v5=this;
return (function(){return l2.value;
})();
});
FUNC.fname='FAIL';
return FUNC;
})();
l2;
l3.fvalue=(function(){var FUNC=(function JSCL_USER_NOP(values){var v7=l4.value;
var I;
for (I=arguments.length-1-1;I>=0;I--)v7=new internals.Cons(arguments[I+1],v7);
var v8=this;
return (function(){return l4.value;
})();
});
FUNC.fname='NOP';
return FUNC;
})();
l3;
var l8=internals.intern('GEN-UID');
var l9=internals.QIList(l8,l4);
l6.fvalue(internals.pv,l9);
var l10=internals.make_lisp_string('-id');
var l11=internals.make_lisp_string('~a-~a~a');
var l12=internals.intern('GENSYM','COMMON-LISP');
var l13=internals.intern('STRING','COMMON-LISP');
var l14=internals.intern('FORMAT','COMMON-LISP');
l8.fvalue=(function(){var FUNC=(function JSCL_USER_GENUID(values,v10,v11,v12){internals.checkArgsAtLeast(arguments.length-1,2);
internals.checkArgsAtMost(arguments.length-1,3);
switch(arguments.length-1){case 2:v12=l10;
;
default:break;
}var v13=this;
return (function(){return l14.fvalue(values,l4.value,l11,v10,l13.fvalue(internals.pv,l12.fvalue(internals.pv,v11)),v12);
})();
});
FUNC.fname='GEN-UID';
return FUNC;
})();
l8;
var l15=internals.intern('SPLIT-STR');
var l16=internals.QIList(l15,l4);
l6.fvalue(internals.pv,l16);
var l17=internals.make_lisp_string('');
var l18=internals.intern('LENGTH','COMMON-LISP');
var l19=internals.intern('EQUAL','COMMON-LISP');
var l20=internals.intern('NULL','COMMON-LISP');
var l21=internals.intern('REVERSE','COMMON-LISP');
var l22=internals.intern('CHAR','COMMON-LISP');
var l23=internals.intern('MEMBER','COMMON-LISP');
var l24=internals.intern('SUBSEQ','COMMON-LISP');
var l25=internals.intern('CONCAT');
l15.fvalue=(function(){var FUNC=(function JSCL_USER_SPLITSTR(values,v15,v16,v17,v18){internals.checkArgsAtLeast(arguments.length-1,2);
internals.checkArgsAtMost(arguments.length-1,4);
switch(arguments.length-1){case 2:v17=l4.value;
;
case 3:v18=l17;
;
default:break;
}var v19=this;
return (function(){return (function(){var x1=l18.fvalue(internals.pv,v16);
if (typeof x1!='number') throw 'Not a number!';
return x1==0?l7.value:l4.value;
})()!==l4.value?l21.fvalue(values,(l19.fvalue(internals.pv,v18,l17)!==l4.value?l20.fvalue(internals.pv,v17):l4.value)!==l4.value?l4:l19.fvalue(internals.pv,v18,l17)!==l4.value?v17:new internals.Cons(v18,v17)):(function(v21){return l23.fvalue(internals.pv,v21,v15)!==l4.value?l15.fvalue(values,v15,l24.fvalue(internals.pv,v16,1),l19.fvalue(internals.pv,v18,l17)!==l4.value?v17:new internals.Cons(v18,v17),l17):l15.fvalue(values,v15,l24.fvalue(internals.pv,v16,1),v17,l25.fvalue(internals.pv,v18,l13.fvalue(internals.pv,v21)));
})(l22.fvalue(internals.pv,v16,0));
})();
});
FUNC.fname='SPLIT-STR';
return FUNC;
})();
l15;
var l26=internals.intern('SPLIT');
var l27=internals.QIList(l26,l4);
l6.fvalue(internals.pv,l27);
var l28=internals.intern('NOT-EMPTY','KEYWORD');
l28.value=l28;
var l29=internals.intern('MAX','KEYWORD');
l29.value=l29;
var l30=internals.intern('DELIM','KEYWORD');
l30.value=l30;
var l31=internals.QIList(' ','	',l4);
var l32=internals.intern('FIND','COMMON-LISP');
var l33=internals.intern('1-','COMMON-LISP');
var l34=internals.intern('START','KEYWORD');
l34.value=l34;
var l35=internals.intern('POSITION-IF','COMMON-LISP');
var l36=internals.intern('NOT','COMMON-LISP');
var l37=internals.intern('1+','COMMON-LISP');
l26.fvalue=(function(){var FUNC=(function JSCL_USER_SPLIT(values,v22){internals.checkArgsAtLeast(arguments.length-1,1);
var v23;
var v24;
var v25;
var I;
for (I=1;I<arguments.length-1;I+=2)if (arguments[I+1]===l28.value) {v23=arguments[I+1+1];
break;
}if (I==arguments.length-1) v23=l4.value;
for (I=1;I<arguments.length-1;I+=2)if (arguments[I+1]===l29.value) {v24=arguments[I+1+1];
break;
}if (I==arguments.length-1) v24=l4.value;
for (I=1;I<arguments.length-1;I+=2)if (arguments[I+1]===l30.value) {v25=arguments[I+1+1];
break;
}if (I==arguments.length-1) v25=l31;
var START=1;
if ((arguments.length-1-START)%2==1) throw 'Odd number of keyword arguments.';
for (I=START;I<arguments.length-1;I+=2)if (arguments[I+1]!==l28.value&&arguments[I+1]!==l29.value&&arguments[I+1]!==l30.value) throw 'Unknown keyword argument '+arguments[I+1]['name'];
var v26=this;
return (function(){return (function(v31){return l21.fvalue(values,(function(v32,v33,v34,v35,v36){return (function(){try{var v37=[];
return (function(){var v38=1;
var v39=[];
TBLOOP:while (true){try{switch(v38){case 1:{if ((v24!==l4.value?(function(){var x1=v34;
if (typeof x1!='number') throw 'Not a number!';
var x2=l33.fvalue(internals.pv,v24);
if (typeof x2!='number') throw 'Not a number!';
return x1>=x2?l7.value:l4.value;
})():l4.value)!==l4.value) (function(){throw new internals.BlockNLX(v37,new internals.Cons(l24.fvalue(internals.pv,v22,v33),v32),'NIL');
})();
 else l4.value;
(function(){return (function(){var FUNC=(function JSCL_USER_NIL(values,v41){switch(arguments.length-1){case 0:v41=l4.value;
;
default:break;
}var v40=l4.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v40=new internals.Cons(arguments[I+1],v40);
var v42=this;
return v35=v41;
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=l35.fvalue(values,v31,v22,l34.value,v33);
if (typeof VS==='object'&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
(function(){return (function(){var FUNC=(function JSCL_USER_NIL(values,v44){switch(arguments.length-1){case 0:v44=l4.value;
;
default:break;
}var v43=l4.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v43=new internals.Cons(arguments[I+1],v43);
var v45=this;
return v36=v44;
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=l24.fvalue(values,v22,v33,v35);
if (typeof VS==='object'&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
if ((v23!==l4.value?(function(){var x1=l18.fvalue(internals.pv,v36);
if (typeof x1!='number') throw 'Not a number!';
return x1>0?l7.value:l4.value;
})():l4.value)!==l4.value) {(function(){var v46=v36;
var v47=new internals.Cons(v46,v32);
return v32=v47;
})();
(function(){var v48=1;
var v49=(function(){var x1=v34;
if (typeof x1!='number') throw 'Not a number!';
var x2=v48;
if (typeof x2!='number') throw 'Not a number!';
return x1+x2;
})();
return v34=v49;
})();
} else if (l36.fvalue(internals.pv,v23)!==l4.value) {(function(){var v50=v36;
var v51=new internals.Cons(v50,v32);
return v32=v51;
})();
(function(){var v52=1;
var v53=(function(){var x1=v34;
if (typeof x1!='number') throw 'Not a number!';
var x2=v52;
if (typeof x2!='number') throw 'Not a number!';
return x1+x2;
})();
return v34=v53;
})();
} else l4.value;
if (v35!==l4.value) l4.value;
 else (function(){throw new internals.BlockNLX(v37,v32,'NIL');
})();
(function(){return (function(){var FUNC=(function JSCL_USER_NIL(values,v55){switch(arguments.length-1){case 0:v55=l4.value;
;
default:break;
}var v54=l4.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v54=new internals.Cons(arguments[I+1],v54);
var v56=this;
return v33=v55;
});
var ARGS=[values];
return (function(){var values=internals.mv;
var VS;
VS=l37.fvalue(values,v35);
if (typeof VS==='object'&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
}(function(){throw new internals.TagNLX(v39,1);
})();
default:break TBLOOP;
}}catch (JUMP){if (JUMP instanceof internals.TagNLX&&JUMP.id==v39) v38=JUMP.label;
 else throw JUMP;
}}return l4.value;
})();
}catch (CF){if (CF instanceof internals.BlockNLX&&CF.id==v37) return CF.values;
 else throw CF;
}})();
})(l4.value,0,0,0,l4.value));
})((function JSCL_USER_NIL(values,v28){internals.checkArgs(arguments.length-1,1);
var v29=this;
return (function(){return l32.fvalue(values,v28,v25);
})();
}));
})();
});
FUNC.fname='SPLIT';
return FUNC;
})();
l26;
var l38=internals.intern('PAIR');
var l39=internals.QIList(l38,l4);
l6.fvalue(internals.pv,l39);
var l40=internals.make_lisp_string('pair:Length lists in pair');
var l41=internals.intern('ERROR','COMMON-LISP');
l38.fvalue=(function(){var FUNC=(function JSCL_USER_PAIR(values,v57,v58){internals.checkArgs(arguments.length-1,2);
var v59=this;
return (function(){return (v57!==l4.value?v58:l4.value)!==l4.value?new internals.Cons(new internals.Cons(internals.car(v57),internals.car(v58)),l38.fvalue(internals.pv,internals.cdr(v57),internals.cdr(v58))):(function(v61){return v61!==l4.value?v61:v58;
})(v57)!==l4.value?l41.fvalue(values,l40):l4.value;
})();
});
FUNC.fname='PAIR';
return FUNC;
})();
l38;
var l42=internals.intern('MKSTR');
var l43=internals.QIList(l42,l4);
l6.fvalue(internals.pv,l43);
var l44=internals.intern('MAKE-STRING-OUTPUT-STREAM','COMMON-LISP');
var l45=internals.intern('PRINC','COMMON-LISP');
var l46=internals.intern('GET-OUTPUT-STREAM-STRING','COMMON-LISP');
l42.fvalue=(function(){var FUNC=(function JSCL_USER_MKSTR(values){var v62=l4.value;
var I;
for (I=arguments.length-1-1;I>=0;I--)v62=new internals.Cons(arguments[I+1],v62);
var v63=this;
return (function(){return (function(v65){(function(){return (function(v67,v68){(function(){while (v67!==l4.value){v68=internals.car(v67);
l45.fvalue(internals.pv,v68,v65);
l4.value;
v67=internals.cdr(v67);
}return l4.value;
})();
return l4.value;
})(v62,l4.value);
})();
return l46.fvalue(values,v65);
})(l44.fvalue(internals.pv));
})();
});
FUNC.fname='MKSTR';
FUNC.docstring='Make a string out of the printed representations of the arguments.';
return FUNC;
})();
l42;
var l47=internals.intern('SYMB');
var l48=internals.QIList(l47,l4);
l6.fvalue(internals.pv,l48);
var l49=internals.intern('REST2');
var l50=internals.intern('INTERN','COMMON-LISP');
l47.fvalue=(function(){var FUNC=(function JSCL_USER_SYMB(values){var v69=l4.value;
var I;
for (I=arguments.length-1-1;I>=0;I--)v69=new internals.Cons(arguments[I+1],v69);
var v70=this;
return (function(){return values(l50.fvalue(internals.pv,(function(){var F=internals.symbolFunction(l42);
var ARGS=[internals.pv,v69];
var TAIL=internals.symbolValue(l49);
while (TAIL!=l4.value){ARGS.push(TAIL.car);
TAIL=TAIL.cdr;
}return (typeof F==='function'?F:F.fvalue).apply(this,ARGS);
})()));
})();
});
FUNC.fname='SYMB';
FUNC.docstring='Make a symbol out of the printed representations of the arguments.';
return FUNC;
})();
l47;
var l51=internals.intern('STARTS-WITH');
var l52=internals.intern('PUNCTUATION-P');
var l53=internals.intern('PRINT-WITH-SPACES');
var l54=internals.intern('MAPPEND');
var l55=internals.intern('NOT-NULL');
var l56=internals.intern('FIRST-OR-NIL');
var l57=internals.intern('FIRST-OR-SELF');
var l58=internals.QIList(l51,l52,l53,l54,l55,l56,l57,l4);
l6.fvalue(internals.pv,l58);
var l59=internals.intern('FIRST','COMMON-LISP');
l51.fvalue=(function(){var FUNC=(function JSCL_USER_STARTSWITH(values,v72,v73){internals.checkArgs(arguments.length-1,2);
var v74=this;
return (function(){return (v72 instanceof internals.Cons?l7.value:l4.value)!==l4.value?l19.fvalue(values,l59.fvalue(internals.pv,v72),v73):l4.value;
})();
});
FUNC.fname='STARTS-WITH';
FUNC.docstring='Is x a list whose first element is x?';
return FUNC;
})();
l51;
var l60=internals.make_lisp_string('.,;:`!?#-()\\"');
l52.fvalue=(function(){var FUNC=(function JSCL_USER_PUNCTUATIONP(values,v76){internals.checkArgs(arguments.length-1,1);
var v77=this;
return (function(){return l32.fvalue(values,v76,l60);
})();
});
FUNC.fname='PUNCTUATION-P';
return FUNC;
})();
l52;
var l61=internals.intern('PRIN1','COMMON-LISP');
var l62=internals.make_lisp_string(' ');
var l63=internals.intern('MAPC','COMMON-LISP');
l53.fvalue=(function(){var FUNC=(function JSCL_USER_PRINTWITHSPACES(values,v79){internals.checkArgs(arguments.length-1,1);
var v80=this;
return (function(){return l63.fvalue(values,(function JSCL_USER_NIL(values,v82){internals.checkArgs(arguments.length-1,1);
var v83=this;
l61.fvalue(internals.pv,v82);
return l45.fvalue(values,l62);
}),v79);
})();
});
FUNC.fname='PRINT-WITH-SPACES';
return FUNC;
})();
l53;
var l64=internals.intern('APPEND','COMMON-LISP');
var l65=internals.intern('MAPCAR','COMMON-LISP');
l54.fvalue=(function(){var FUNC=(function JSCL_USER_MAPPEND(values,v85){internals.checkArgsAtLeast(arguments.length-1,1);
var v84=l4.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v84=new internals.Cons(arguments[I+1],v84);
var v86=this;
return (function(){return (function(){var F=internals.symbolFunction(l64);
var ARGS=[values];
var TAIL=(function(){var F=internals.symbolFunction(l65);
var ARGS=[internals.pv,v85];
var TAIL=v84;
while (TAIL!=l4.value){ARGS.push(TAIL.car);
TAIL=TAIL.cdr;
}return (typeof F==='function'?F:F.fvalue).apply(this,ARGS);
})();
while (TAIL!=l4.value){ARGS.push(TAIL.car);
TAIL=TAIL.cdr;
}return (typeof F==='function'?F:F.fvalue).apply(this,ARGS);
})();
})();
});
FUNC.fname='MAPPEND';
FUNC.docstring='Apply fn to each element of lists and append the results.';
return FUNC;
})();
l54;
l55.fvalue=(function(){var FUNC=(function JSCL_USER_NOTNULL(values,v88){internals.checkArgs(arguments.length-1,1);
var v89=this;
return (function(){return l36.fvalue(values,l20.fvalue(internals.pv,v88));
})();
});
FUNC.fname='NOT-NULL';
return FUNC;
})();
l55;
l56.fvalue=(function(){var FUNC=(function JSCL_USER_FIRSTORNIL(values,v91){internals.checkArgs(arguments.length-1,1);
var v92=this;
return (function(){return (v91 instanceof internals.Cons?l7.value:l4.value)!==l4.value?l59.fvalue(values,v91):l4.value;
})();
});
FUNC.fname='FIRST-OR-NIL';
FUNC.docstring='The first element of x if it is a list; else nil.';
return FUNC;
})();
l56;
l57.fvalue=(function(){var FUNC=(function JSCL_USER_FIRSTORSELF(values,v94){internals.checkArgs(arguments.length-1,1);
var v95=this;
return (function(){return (v94 instanceof internals.Cons?l7.value:l4.value)!==l4.value?l59.fvalue(values,v94):v94;
})();
});
FUNC.fname='FIRST-OR-SELF';
FUNC.docstring='The first element of x, if it is a list; else x itself.';
return FUNC;
})();
l57;
var l66=internals.QIList(l49,l4);
l6.fvalue(internals.pv,l66);
var l67=internals.intern('REST','COMMON-LISP');
l49.fvalue=(function(){var FUNC=(function JSCL_USER_REST(values,v97){internals.checkArgs(arguments.length-1,1);
var v98=this;
return (function(){return l67.fvalue(values,l67.fvalue(internals.pv,v97));
})();
});
FUNC.fname='REST2';
return FUNC;
})();
l49;
var l68=internals.intern('FLATTEN');
var l69=internals.intern('MKLIST');
var l70=internals.intern('MAPPEND2');
var l71=internals.intern('RANDOM-ELT');
var l72=internals.intern('SUM');
var l73=internals.QIList(l68,l69,l70,l71,l72,l4);
l6.fvalue(internals.pv,l73);
l68.fvalue=(function(){var FUNC=(function JSCL_USER_FLATTEN(values,v100){internals.checkArgs(arguments.length-1,1);
var v101=this;
return (function(){return l70.fvalue(values,internals.symbolFunction(l69),v100);
})();
});
FUNC.fname='FLATTEN';
FUNC.docstring='Append together elements (or lists) in the list.';
return FUNC;
})();
l68;
var l74=internals.intern('LISTP','COMMON-LISP');
var l75=internals.intern('LIST','COMMON-LISP');
l69.fvalue=(function(){var FUNC=(function JSCL_USER_MKLIST(values,v103){internals.checkArgs(arguments.length-1,1);
var v104=this;
return (function(){return l74.fvalue(internals.pv,v103)!==l4.value?v103:l75.fvalue(values,v103);
})();
});
FUNC.fname='MKLIST';
FUNC.docstring='Return x if it is a list, otherwise (x).';
return FUNC;
})();
l69;
l70.fvalue=(function(){var FUNC=(function JSCL_USER_MAPPEND(values,v106,v107){internals.checkArgs(arguments.length-1,2);
var v108=this;
return (function(){return (function(){var F=internals.symbolFunction(l64);
var ARGS=[values];
var TAIL=l65.fvalue(internals.pv,v106,v107);
while (TAIL!=l4.value){ARGS.push(TAIL.car);
TAIL=TAIL.cdr;
}return (typeof F==='function'?F:F.fvalue).apply(this,ARGS);
})();
})();
});
FUNC.fname='MAPPEND2';
FUNC.docstring='Apply fn to each element of list and append the results.';
return FUNC;
})();
l70;
var l76=internals.intern('RANDOM','COMMON-LISP');
var l77=internals.intern('ELT','COMMON-LISP');
l71.fvalue=(function(){var FUNC=(function JSCL_USER_RANDOMELT(values,v110){internals.checkArgs(arguments.length-1,1);
var v111=this;
return (function(){return l77.fvalue(values,v110,l76.fvalue(internals.pv,l18.fvalue(internals.pv,v110)));
})();
});
FUNC.fname='RANDOM-ELT';
FUNC.docstring='Choose an element from a list at random.';
return FUNC;
})();
l71;
var l78=internals.intern('+','COMMON-LISP');
var l79=internals.intern('REDUCE','COMMON-LISP');
l72.fvalue=(function(){var FUNC=(function JSCL_USER_SUM(values,v113){internals.checkArgs(arguments.length-1,1);
var v114=this;
return (function(){return l79.fvalue(values,internals.symbolFunction(l78),v113);
})();
});
FUNC.fname='SUM';
return FUNC;
})();
l72;
var l80=internals.QIList(l76,l4);
l6.fvalue(internals.pv,l80);
var l81=internals.intern('*ROOT*');
var l82=internals.make_lisp_string('Math');
var l83=internals.make_lisp_string('random');
var l84=internals.make_lisp_string('Math');
var l85=internals.make_lisp_string('floor');
l76.fvalue=(function(){var FUNC=(function JSCL_USER_RANDOM(values,v116){internals.checkArgs(arguments.length-1,1);
var v117=this;
return (function(){return internals.js_to_lisp(internals.symbolValue(l81)[internals.xstring(l84)][internals.xstring(l85)](internals.lisp_to_js((function(){var x1=internals.js_to_lisp(internals.symbolValue(l81)[internals.xstring(l82)][internals.xstring(l83)]());
if (typeof x1!='number') throw 'Not a number!';
var x2=v116;
if (typeof x2!='number') throw 'Not a number!';
return x1*x2;
})())));
})();
});
FUNC.fname='RANDOM';
return FUNC;
})();
l76;
var l86=internals.intern('MAKE-JS-OBJECT');
var l87=internals.intern('MAKE-JSO');
var l88=internals.intern('WITH-JS-OBJECT');
var l89=internals.intern('MAP-JS-OBJECT');
var l90=internals.intern('GET-JS-OBJECT-KEYS');
var l91=internals.intern('GET-JS-OBJECT-VALUES');
var l92=internals.intern('GET-JS-OBJECT-PAIR');
var l93=internals.intern('JS-OBJECT-TO-ALIST');
var l94=internals.QIList(l86,l87,l88,l89,l90,l91,l92,l93,l4);
l6.fvalue(internals.pv,l94);
var l95=internals.intern('ODDP','COMMON-LISP');
var l96=internals.make_lisp_string('make-js-object: length of the arguments list not even - ~a');
l86.fvalue=(function(){var FUNC=(function JSCL_USER_MAKEJSOBJECT(values){var v119=l4.value;
var I;
for (I=arguments.length-1-1;I>=0;I--)v119=new internals.Cons(arguments[I+1],v119);
var v120=this;
return (function(){return (function(){var v122={};
var v123=0;
var v124=l4.value;
if (l95.fvalue(internals.pv,l18.fvalue(internals.pv,v119))!==l4.value) l41.fvalue(internals.pv,l96,l18.fvalue(internals.pv,v119));
 else l4.value;
l65.fvalue(internals.pv,(function JSCL_USER_NIL(values,v125){internals.checkArgs(arguments.length-1,1);
var v126=this;
if (l95.fvalue(internals.pv,v123)!==l4.value) (function(){var v127=v122;
var v128=v124;
return (function(){var FUNC=(function JSCL_USER_NIL(values,v130){switch(arguments.length-1){case 0:v130=l4.value;
;
default:break;
}var v129=l4.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v129=new internals.Cons(arguments[I+1],v129);
var v131=this;
return (function(){var OBJ=v127;
var TMP=(OBJ[internals.xstring(v128)]=internals.lisp_to_js(v130));
return TMP===undefined?l4.value:TMP;
})();
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=v125;
if (typeof VS==='object'&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
 else (function(){return (function(){var FUNC=(function JSCL_USER_NIL(values,v133){switch(arguments.length-1){case 0:v133=l4.value;
;
default:break;
}var v132=l4.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v132=new internals.Cons(arguments[I+1],v132);
var v134=this;
return v124=v133;
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=v125;
if (typeof VS==='object'&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
return (function(){var v135=1;
var v136=(function(){var x1=v123;
if (typeof x1!='number') throw 'Not a number!';
var x2=v135;
if (typeof x2!='number') throw 'Not a number!';
return x1+x2;
})();
return v123=v136;
})();
}),v119);
return v122;
})();
})();
});
FUNC.fname='MAKE-JS-OBJECT';
return FUNC;
})();
l86;
var l97=internals.make_lisp_string('make-jso: length of the arguments list not even - ~a');
var l98=internals.intern('EVENP','COMMON-LISP');
var l99=internals.make_lisp_string('make-jso: object name field not atom ~s');
l87.fvalue=(function(){var FUNC=(function JSCL_USER_MAKEJSO(values){var v137=l4.value;
var I;
for (I=arguments.length-1-1;I>=0;I--)v137=new internals.Cons(arguments[I+1],v137);
var v138=this;
return (function(){return (function(){var v140={};
var v141=0;
var v142=l4.value;
if (l95.fvalue(internals.pv,l18.fvalue(internals.pv,v137))!==l4.value) l41.fvalue(internals.pv,l97,l18.fvalue(internals.pv,v137));
 else l4.value;
l65.fvalue(internals.pv,(function JSCL_USER_NIL(values,v143){internals.checkArgs(arguments.length-1,1);
var v144=this;
(function(){var v145=v143;
if (l74.fvalue(internals.pv,v143)!==l4.value) {if (l98.fvalue(internals.pv,v141)!==l4.value) l41.fvalue(internals.pv,l99,v143);
 else l4.value;
(function(){return (function(){var FUNC=(function JSCL_USER_NIL(values,v147){switch(arguments.length-1){case 0:v147=l4.value;
;
default:break;
}var v146=l4.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v146=new internals.Cons(arguments[I+1],v146);
var v148=this;
return v145=v147;
});
var ARGS=[values];
return (function(){var values=internals.mv;
var VS;
VS=(function(){var F=internals.symbolFunction(l87);
var ARGS=[values];
var TAIL=v143;
while (TAIL!=l4.value){ARGS.push(TAIL.car);
TAIL=TAIL.cdr;
}return (typeof F==='function'?F:F.fvalue).apply(this,ARGS);
})();
if (typeof VS==='object'&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
} else l4.value;
return l95.fvalue(internals.pv,v141)!==l4.value?(function(){var v149=v140;
var v150=v142;
return (function(){var FUNC=(function JSCL_USER_NIL(values,v152){switch(arguments.length-1){case 0:v152=l4.value;
;
default:break;
}var v151=l4.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v151=new internals.Cons(arguments[I+1],v151);
var v153=this;
return (function(){var OBJ=v149;
var TMP=(OBJ[internals.xstring(v150)]=internals.lisp_to_js(v152));
return TMP===undefined?l4.value:TMP;
})();
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=v145;
if (typeof VS==='object'&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})():(function(){return (function(){var FUNC=(function JSCL_USER_NIL(values,v155){switch(arguments.length-1){case 0:v155=l4.value;
;
default:break;
}var v154=l4.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v154=new internals.Cons(arguments[I+1],v154);
var v156=this;
return v142=v155;
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=v145;
if (typeof VS==='object'&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
})();
return (function(){var v157=1;
var v158=(function(){var x1=v141;
if (typeof x1!='number') throw 'Not a number!';
var x2=v157;
if (typeof x2!='number') throw 'Not a number!';
return x1+x2;
})();
return v141=v158;
})();
}),v137);
return v140;
})();
})();
});
FUNC.fname='MAKE-JSO';
return FUNC;
})();
l87;
var l100=internals.make_lisp_string('Object');
var l101=internals.make_lisp_string('keys');
var l102=internals.intern('AREF','COMMON-LISP');
var l103=internals.make_lisp_string('toString');
var l104=internals.make_lisp_string('bind');
l89.fvalue=(function(){var FUNC=(function JSCL_USER_MAPJSOBJECT(values,v159,v160){internals.checkArgs(arguments.length-1,2);
var v161=this;
return (function(){return (function(){var v163=internals.js_to_lisp(internals.symbolValue(l81)[internals.xstring(l100)][internals.xstring(l101)](internals.lisp_to_js(v160)));
var v164=l18.fvalue(internals.pv,v163);
return (function(){return (function(v166,v167){(function(){while ((function(){var x1=v166;
if (typeof x1!='number') throw 'Not a number!';
var x2=v167;
if (typeof x2!='number') throw 'Not a number!';
return x1<x2?l7.value:l4.value;
})()!==l4.value){(function(){var v168=l102.fvalue(internals.pv,v163,v166);
var v169=(function(){var F=internals.js_to_lisp(v168[internals.xstring(l103)][internals.xstring(l104)](internals.lisp_to_js(v168)));
return (typeof F==='function'?F:F.fvalue)(internals.pv);
})();
var v170=internals.js_to_lisp((function(){var TMP=v160[internals.xstring(v169)];
return TMP===undefined?l4.value:TMP;
})());
return (function(){var F=v159;
return (typeof F==='function'?F:F.fvalue)(internals.pv,v169,v170);
})();
})();
l4.value;
(function(){var v171=1;
var v172=(function(){var x1=v166;
if (typeof x1!='number') throw 'Not a number!';
var x2=v171;
if (typeof x2!='number') throw 'Not a number!';
return x1+x2;
})();
return v166=v172;
})();
}return l4.value;
})();
return l4.value;
})(0,v164);
})();
})();
})();
});
FUNC.fname='MAP-JS-OBJECT';
return FUNC;
})();
l89;
l90.fvalue=(function(){var FUNC=(function JSCL_USER_GETJSOBJECTKEYS(values,v173){internals.checkArgs(arguments.length-1,1);
var v174=this;
return (function(){return (function(){var v176=l4.value;
return (function(){var v177=internals.js_to_lisp(internals.symbolValue(l81)[internals.xstring(l100)][internals.xstring(l101)](internals.lisp_to_js(v173)));
var v178=l18.fvalue(internals.pv,v177);
return (function(){return (function(v180,v181){(function(){while ((function(){var x1=v180;
if (typeof x1!='number') throw 'Not a number!';
var x2=v181;
if (typeof x2!='number') throw 'Not a number!';
return x1<x2?l7.value:l4.value;
})()!==l4.value){(function(){var v182=l102.fvalue(internals.pv,v177,v180);
var v183=(function(){var F=internals.js_to_lisp(v182[internals.xstring(l103)][internals.xstring(l104)](internals.lisp_to_js(v182)));
return (typeof F==='function'?F:F.fvalue)(internals.pv);
})();
var v184=internals.js_to_lisp((function(){var TMP=v173[internals.xstring(v183)];
return TMP===undefined?l4.value:TMP;
})());
return (function(){var v185=v183;
var v186=new internals.Cons(v185,v176);
return v176=v186;
})();
})();
l4.value;
(function(){var v187=1;
var v188=(function(){var x1=v180;
if (typeof x1!='number') throw 'Not a number!';
var x2=v187;
if (typeof x2!='number') throw 'Not a number!';
return x1+x2;
})();
return v180=v188;
})();
}return l4.value;
})();
return v176;
})(0,v178);
})();
})();
})();
})();
});
FUNC.fname='GET-JS-OBJECT-KEYS';
return FUNC;
})();
l90;
l91.fvalue=(function(){var FUNC=(function JSCL_USER_GETJSOBJECTVALUES(values,v189){internals.checkArgs(arguments.length-1,1);
var v190=this;
return (function(){return (function(){var v192=l4.value;
return (function(){var v193=internals.js_to_lisp(internals.symbolValue(l81)[internals.xstring(l100)][internals.xstring(l101)](internals.lisp_to_js(v189)));
var v194=l18.fvalue(internals.pv,v193);
return (function(){return (function(v196,v197){(function(){while ((function(){var x1=v196;
if (typeof x1!='number') throw 'Not a number!';
var x2=v197;
if (typeof x2!='number') throw 'Not a number!';
return x1<x2?l7.value:l4.value;
})()!==l4.value){(function(){var v198=l102.fvalue(internals.pv,v193,v196);
var v199=(function(){var F=internals.js_to_lisp(v198[internals.xstring(l103)][internals.xstring(l104)](internals.lisp_to_js(v198)));
return (typeof F==='function'?F:F.fvalue)(internals.pv);
})();
var v200=internals.js_to_lisp((function(){var TMP=v189[internals.xstring(v199)];
return TMP===undefined?l4.value:TMP;
})());
return (function(){var v201=v200;
var v202=new internals.Cons(v201,v192);
return v192=v202;
})();
})();
l4.value;
(function(){var v203=1;
var v204=(function(){var x1=v196;
if (typeof x1!='number') throw 'Not a number!';
var x2=v203;
if (typeof x2!='number') throw 'Not a number!';
return x1+x2;
})();
return v196=v204;
})();
}return l4.value;
})();
return v192;
})(0,v194);
})();
})();
})();
})();
});
FUNC.fname='GET-JS-OBJECT-VALUES';
return FUNC;
})();
l91;
l92.fvalue=(function(){var FUNC=(function JSCL_USER_GETJSOBJECTPAIR(values,v205){internals.checkArgs(arguments.length-1,1);
var v206=this;
return (function(){return values(l90.fvalue(internals.pv,v205),l91.fvalue(internals.pv,v205));
})();
});
FUNC.fname='GET-JS-OBJECT-PAIR';
return FUNC;
})();
l92;
var l105=internals.intern('MAKE-FN','KEYWORD');
l105.value=l105;
l93.fvalue=(function(){var FUNC=(function JSCL_USER_JSOBJECTTOALIST(values,v208){internals.checkArgsAtLeast(arguments.length-1,1);
var v209;
var I;
for (I=1;I<arguments.length-1;I+=2)if (arguments[I+1]===l105.value) {v209=arguments[I+1+1];
break;
}if (I==arguments.length-1) v209=internals.symbolFunction(l75);
var START=1;
if ((arguments.length-1-START)%2==1) throw 'Odd number of keyword arguments.';
for (I=START;I<arguments.length-1;I+=2)if (arguments[I+1]!==l105.value) throw 'Unknown keyword argument '+arguments[I+1]['name'];
var v210=this;
return (function(){return (function(v212){return (function(){var v213=internals.js_to_lisp(internals.symbolValue(l81)[internals.xstring(l100)][internals.xstring(l101)](internals.lisp_to_js(v208)));
var v214=l18.fvalue(internals.pv,v213);
return (function(){return (function(v216,v217){(function(){while ((function(){var x1=v216;
if (typeof x1!='number') throw 'Not a number!';
var x2=v217;
if (typeof x2!='number') throw 'Not a number!';
return x1<x2?l7.value:l4.value;
})()!==l4.value){(function(){var v218=l102.fvalue(internals.pv,v213,v216);
var v219=(function(){var F=internals.js_to_lisp(v218[internals.xstring(l103)][internals.xstring(l104)](internals.lisp_to_js(v218)));
return (typeof F==='function'?F:F.fvalue)(internals.pv);
})();
var v220=internals.js_to_lisp((function(){var TMP=v208[internals.xstring(v219)];
return TMP===undefined?l4.value:TMP;
})());
return (function(){var v221=(function(){var F=v209;
return (typeof F==='function'?F:F.fvalue)(internals.pv,v219,v220);
})();
var v222=new internals.Cons(v221,v212);
return v212=v222;
})();
})();
l4.value;
(function(){var v223=1;
var v224=(function(){var x1=v216;
if (typeof x1!='number') throw 'Not a number!';
var x2=v223;
if (typeof x2!='number') throw 'Not a number!';
return x1+x2;
})();
return v216=v224;
})();
}return l4.value;
})();
return v212;
})(0,v214);
})();
})();
})(l4);
})();
});
FUNC.fname='JS-OBJECT-TO-ALIST';
return FUNC;
})();
l93;
var l106=internals.intern('DOM-GET-BODY');
var l107=internals.intern('DOM-GET-HEAD');
var l108=internals.intern('DOM-GET-TITLE');
var l109=internals.intern('DOM-SET-TITLE');
var l110=internals.intern('DOM-GET-ELEMENT-VALUE');
var l111=internals.intern('DOM-SET-ELEMENT-VALUE');
var l112=internals.intern('DOM-GET-ELEMENT-BY-ID');
var l113=internals.intern('DOM-SET-ATTRIBUTE');
var l114=internals.intern('DOM-GET-ATTRIBUTE');
var l115=internals.intern('DOM-REMOVE-ATTRIBUTE');
var l116=internals.intern('DOM-SET-EVENT');
var l117=internals.intern('DOM-ELEMENT-P');
var l118=internals.intern('DOM-ESCAPE-HTML');
var l119=internals.intern('DOM-GET-INNER-HTML');
var l120=internals.intern('DOM-SET-INNER-HTML');
var l121=internals.intern('DOM-CREATE-TEXT-NODE');
var l122=internals.intern('DOM-REPLACE-TEXT-NODE');
var l123=internals.intern('DOM-REMOVE');
var l124=internals.intern('DOM-ADD-CLASS');
var l125=internals.intern('DOM-REMOVE-CLASS');
var l126=internals.intern('DOM-HAVE-CLASS-P');
var l127=internals.intern('DOM-APPEND');
var l128=internals.intern('DOM-MOUNT');
var l129=internals.intern('DOM-CLEAR');
var l130=internals.intern('DOM-CREATE');
var l131=internals.intern('DOM-CREATE-INPUT');
var l132=internals.intern('DOM-CREATE-TEXT');
var l133=internals.intern('DOM-CREATE-BUTTON');
var l134=internals.intern('DOM-CREATE-CHECKBOX');
var l135=internals.intern('DOM-PARENT-NODE');
var l136=internals.intern('DOM-ELEMENT-NODE-NAME');
var l137=internals.intern('DOM-ELEMENT-LAST-CHILD-P');
var l138=internals.intern('DOM-ELEMENT-CHILD-COUNT');
var l139=internals.intern('DOM-ELEMENT-CHILDS-COLLECTION');
var l140=internals.intern('DOM-ELEMENT-FIRST-CHILD');
var l141=internals.intern('DOM-ELEMENT-LAST-CHILD');
var l142=internals.intern('DOM-ELEMENT-NEXT-SIBLING');
var l143=internals.intern('DOM-ELEMENT-PARENT-NODE');
var l144=internals.intern('DOM-INSERT-BEFORE');
var l145=internals.intern('DOM-INSERT-AFTER');
var l146=internals.intern('DOM-INSERT-TOP');
var l147=internals.intern('DOM-INSERT');
var l148=internals.QIList(l106,l107,l108,l109,l110,l111,l112,l113,l114,l115,l116,l117,l118,l119,l120,l121,l122,l123,l124,l125,l126,l127,l128,l129,l130,l131,l132,l133,l134,l135,l136,l137,l138,l139,l140,l141,l142,l143,l144,l145,l146,l147,l4);
l6.fvalue(internals.pv,l148);
var l149=internals.make_lisp_string('window');
var l150=internals.make_lisp_string('document');
var l151=internals.make_lisp_string('body');
l106.fvalue=(function(){var FUNC=(function JSCL_USER_DOMGETBODY(values){internals.checkArgsAtMost(arguments.length-1,0);
var v225=this;
return (function(){return internals.js_to_lisp((function(){var TMP=internals.symbolValue(l81)[internals.xstring(l149)];
if (TMP===undefined) return l4.value;
TMP=TMP[internals.xstring(l150)];
if (TMP===undefined) return l4.value;
TMP=TMP[internals.xstring(l151)];
return TMP===undefined?l4.value:TMP;
})());
})();
});
FUNC.fname='DOM-GET-BODY';
return FUNC;
})();
l106;
var l152=internals.make_lisp_string('window');
var l153=internals.make_lisp_string('document');
var l154=internals.make_lisp_string('head');
l107.fvalue=(function(){var FUNC=(function JSCL_USER_DOMGETHEAD(values){internals.checkArgsAtMost(arguments.length-1,0);
var v227=this;
return (function(){return internals.js_to_lisp((function(){var TMP=internals.symbolValue(l81)[internals.xstring(l152)];
if (TMP===undefined) return l4.value;
TMP=TMP[internals.xstring(l153)];
if (TMP===undefined) return l4.value;
TMP=TMP[internals.xstring(l154)];
return TMP===undefined?l4.value:TMP;
})());
})();
});
FUNC.fname='DOM-GET-HEAD';
return FUNC;
})();
l107;
var l155=internals.make_lisp_string('window');
var l156=internals.make_lisp_string('document');
var l157=internals.make_lisp_string('title');
l108.fvalue=(function(){var FUNC=(function JSCL_USER_DOMGETTITLE(values){internals.checkArgsAtMost(arguments.length-1,0);
var v229=this;
return (function(){return internals.js_to_lisp((function(){var TMP=internals.js_to_lisp((function(){var TMP=internals.symbolValue(l81)[internals.xstring(l155)];
if (TMP===undefined) return l4.value;
TMP=TMP[internals.xstring(l156)];
return TMP===undefined?l4.value:TMP;
})())[internals.xstring(l157)];
return TMP===undefined?l4.value:TMP;
})());
})();
});
FUNC.fname='DOM-GET-TITLE';
return FUNC;
})();
l108;
var l158=internals.make_lisp_string('window');
var l159=internals.make_lisp_string('document');
var l160=internals.make_lisp_string('title');
l109.fvalue=(function(){var FUNC=(function JSCL_USER_DOMSETTITLE(values,v231){internals.checkArgs(arguments.length-1,1);
var v232=this;
return (function(){return (function(){var v234=internals.js_to_lisp((function(){var TMP=internals.symbolValue(l81)[internals.xstring(l158)];
if (TMP===undefined) return l4.value;
TMP=TMP[internals.xstring(l159)];
return TMP===undefined?l4.value:TMP;
})());
var v235=l160;
return (function(){var FUNC=(function JSCL_USER_NIL(values,v237){switch(arguments.length-1){case 0:v237=l4.value;
;
default:break;
}var v236=l4.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v236=new internals.Cons(arguments[I+1],v236);
var v238=this;
return (function(){var OBJ=v234;
var TMP=(OBJ[internals.xstring(v235)]=internals.lisp_to_js(v237));
return TMP===undefined?l4.value:TMP;
})();
});
var ARGS=[values];
return (function(){var values=internals.mv;
var VS;
VS=v231;
if (typeof VS==='object'&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
})();
});
FUNC.fname='DOM-SET-TITLE';
return FUNC;
})();
l109;
var l161=internals.make_lisp_string('value');
l110.fvalue=(function(){var FUNC=(function JSCL_USER_DOMGETELEMENTVALUE(values,v239){internals.checkArgs(arguments.length-1,1);
var v240=this;
return (function(){return internals.js_to_lisp((function(){var TMP=v239[internals.xstring(l161)];
return TMP===undefined?l4.value:TMP;
})());
})();
});
FUNC.fname='DOM-GET-ELEMENT-VALUE';
return FUNC;
})();
l110;
var l162=internals.intern('ELEMENT');
var l163=internals.make_lisp_string('value');
l111.fvalue=(function(){var FUNC=(function JSCL_USER_DOMSETELEMENTVALUE(values,v242){internals.checkArgs(arguments.length-1,1);
var v243=this;
return (function(){return (function(){var v245=internals.symbolValue(l162);
var v246=l163;
return (function(){var FUNC=(function JSCL_USER_NIL(values,v248){switch(arguments.length-1){case 0:v248=l4.value;
;
default:break;
}var v247=l4.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v247=new internals.Cons(arguments[I+1],v247);
var v249=this;
return (function(){var OBJ=v245;
var TMP=(OBJ[internals.xstring(v246)]=internals.lisp_to_js(v248));
return TMP===undefined?l4.value:TMP;
})();
});
var ARGS=[values];
return (function(){var values=internals.mv;
var VS;
VS=v242;
if (typeof VS==='object'&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
})();
});
FUNC.fname='DOM-SET-ELEMENT-VALUE';
return FUNC;
})();
l111;
var l164=internals.make_lisp_string('window');
var l165=internals.make_lisp_string('document');
var l166=internals.make_lisp_string('getElementById');
l112.fvalue=(function(){var FUNC=(function JSCL_USER_DOMGETELEMENTBYID(values,v250){internals.checkArgs(arguments.length-1,1);
var v251=this;
return (function(){return internals.js_to_lisp(internals.symbolValue(l81)[internals.xstring(l164)][internals.xstring(l165)][internals.xstring(l166)](internals.lisp_to_js(v250)));
})();
});
FUNC.fname='DOM-GET-ELEMENT-BY-ID';
return FUNC;
})();
l112;
var l167=internals.make_lisp_string('setAttribute');
var l168=internals.make_lisp_string('bind');
l113.fvalue=(function(){var FUNC=(function JSCL_USER_DOMSETATTRIBUTE(values,v253,v254,v255){internals.checkArgs(arguments.length-1,3);
var v256=this;
return (function(){return (function(){var F=internals.js_to_lisp(v253[internals.xstring(l167)][internals.xstring(l168)](internals.lisp_to_js(v253),internals.lisp_to_js(v254),internals.lisp_to_js(v255)));
return (typeof F==='function'?F:F.fvalue)(values);
})();
})();
});
FUNC.fname='DOM-SET-ATTRIBUTE';
return FUNC;
})();
l113;
var l169=internals.make_lisp_string('getAttribute');
var l170=internals.make_lisp_string('bind');
l114.fvalue=(function(){var FUNC=(function JSCL_USER_DOMGETATTRIBUTE(values,v258,v259){internals.checkArgs(arguments.length-1,2);
var v260=this;
return (function(){return (function(){var F=internals.js_to_lisp(v258[internals.xstring(l169)][internals.xstring(l170)](internals.lisp_to_js(v258),internals.lisp_to_js(v259)));
return (typeof F==='function'?F:F.fvalue)(values);
})();
})();
});
FUNC.fname='DOM-GET-ATTRIBUTE';
return FUNC;
})();
l114;
var l171=internals.make_lisp_string('removeAttribute');
var l172=internals.make_lisp_string('bind');
l115.fvalue=(function(){var FUNC=(function JSCL_USER_DOMREMOVEATTRIBUTE(values,v262,v263){internals.checkArgs(arguments.length-1,2);
var v264=this;
return (function(){return (function(){var F=internals.js_to_lisp(v262[internals.xstring(l171)][internals.xstring(l172)](internals.lisp_to_js(v262),internals.lisp_to_js(v263)));
return (typeof F==='function'?F:F.fvalue)(values);
})();
})();
});
FUNC.fname='DOM-REMOVE-ATTRIBUTE';
return FUNC;
})();
l115;
l116.fvalue=(function(){var FUNC=(function JSCL_USER_DOMSETEVENT(values,v266,v267,v268){internals.checkArgs(arguments.length-1,3);
var v269=this;
return (function(){return (function(){var v271=v266;
var v272=v267;
return (function(){var FUNC=(function JSCL_USER_NIL(values,v274){switch(arguments.length-1){case 0:v274=l4.value;
;
default:break;
}var v273=l4.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v273=new internals.Cons(arguments[I+1],v273);
var v275=this;
return (function(){var OBJ=v271;
var TMP=(OBJ[internals.xstring(v272)]=internals.lisp_to_js(v274));
return TMP===undefined?l4.value:TMP;
})();
});
var ARGS=[values];
return (function(){var values=internals.mv;
var VS;
VS=v268;
if (typeof VS==='object'&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
})();
});
FUNC.fname='DOM-SET-EVENT';
return FUNC;
})();
l116;
var l173=internals.make_lisp_string('appendChild');
l117.fvalue=(function(){var FUNC=(function JSCL_USER_DOMELEMENTP(values,v276){internals.checkArgs(arguments.length-1,1);
var v277=this;
return (function(){return (typeof v276==='object'?l7.value:l4.value)!==l4.value?l36.fvalue(internals.pv,l20.fvalue(internals.pv,internals.js_to_lisp((function(){var TMP=v276[internals.xstring(l173)];
return TMP===undefined?l4.value:TMP;
})())))!==l4.value?l7.value:l4.value:l4.value;
})();
});
FUNC.fname='DOM-ELEMENT-P';
return FUNC;
})();
l117;
var l174=internals.make_lisp_string('div');
var l175=internals.make_lisp_string('window');
var l176=internals.make_lisp_string('document');
var l177=internals.make_lisp_string('createElement');
var l178=internals.make_lisp_string('window');
var l179=internals.make_lisp_string('document');
var l180=internals.make_lisp_string('createTextNode');
var l181=internals.make_lisp_string('appendChild');
var l182=internals.make_lisp_string('bind');
l118.fvalue=(function(){var FUNC=(function JSCL_USER_DOMESCAPEHTML(values,v279){internals.checkArgs(arguments.length-1,1);
var v280=this;
return (function(){return (function(){var v282=internals.js_to_lisp(internals.symbolValue(l81)[internals.xstring(l175)][internals.xstring(l176)][internals.xstring(l177)](internals.lisp_to_js(l174)));
var v283=internals.js_to_lisp(internals.symbolValue(l81)[internals.xstring(l178)][internals.xstring(l179)][internals.xstring(l180)](internals.lisp_to_js(v279)));
(function(){var F=internals.js_to_lisp(v282[internals.xstring(l181)][internals.xstring(l182)](internals.lisp_to_js(v282),internals.lisp_to_js(v283)));
return (typeof F==='function'?F:F.fvalue)(internals.pv);
})();
return v282;
})();
})();
});
FUNC.fname='DOM-ESCAPE-HTML';
return FUNC;
})();
l118;
var l183=internals.make_lisp_string('innerHTML');
l119.fvalue=(function(){var FUNC=(function JSCL_USER_DOMGETINNERHTML(values,v284){internals.checkArgs(arguments.length-1,1);
var v285=this;
return (function(){return internals.js_to_lisp((function(){var TMP=v284[internals.xstring(l183)];
return TMP===undefined?l4.value:TMP;
})());
})();
});
FUNC.fname='DOM-GET-INNER-HTML';
return FUNC;
})();
l119;
var l184=internals.make_lisp_string('innerHTML');
l120.fvalue=(function(){var FUNC=(function JSCL_USER_DOMSETINNERHTML(values,v287,v288){internals.checkArgs(arguments.length-1,2);
var v289=this;
return (function(){return (function(){var v291=v287;
var v292=l184;
return (function(){var FUNC=(function JSCL_USER_NIL(values,v294){switch(arguments.length-1){case 0:v294=l4.value;
;
default:break;
}var v293=l4.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v293=new internals.Cons(arguments[I+1],v293);
var v295=this;
return (function(){var OBJ=v291;
var TMP=(OBJ[internals.xstring(v292)]=internals.lisp_to_js(v294));
return TMP===undefined?l4.value:TMP;
})();
});
var ARGS=[values];
return (function(){var values=internals.mv;
var VS;
VS=v288;
if (typeof VS==='object'&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
})();
});
FUNC.fname='DOM-SET-INNER-HTML';
return FUNC;
})();
l120;
var l185=internals.make_lisp_string('window');
var l186=internals.make_lisp_string('document');
var l187=internals.make_lisp_string('createTextNode');
l121.fvalue=(function(){var FUNC=(function JSCL_USER_DOMCREATETEXTNODE(values,v296){internals.checkArgs(arguments.length-1,1);
var v297=this;
return (function(){return internals.js_to_lisp(internals.symbolValue(l81)[internals.xstring(l185)][internals.xstring(l186)][internals.xstring(l187)](internals.lisp_to_js(v296)));
})();
});
FUNC.fname='DOM-CREATE-TEXT-NODE';
return FUNC;
})();
l121;
var l188=internals.make_lisp_string('innerHTML');
l122.fvalue=(function(){var FUNC=(function JSCL_USER_DOMREPLACETEXTNODE(values,v299,v300){internals.checkArgs(arguments.length-1,2);
var v301=this;
return (function(){return (function(){var v303=v299;
var v304=l188;
return (function(){var FUNC=(function JSCL_USER_NIL(values,v306){switch(arguments.length-1){case 0:v306=l4.value;
;
default:break;
}var v305=l4.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v305=new internals.Cons(arguments[I+1],v305);
var v307=this;
return (function(){var OBJ=v303;
var TMP=(OBJ[internals.xstring(v304)]=internals.lisp_to_js(v306));
return TMP===undefined?l4.value:TMP;
})();
});
var ARGS=[values];
return (function(){var values=internals.mv;
var VS;
VS=v300;
if (typeof VS==='object'&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
})();
});
FUNC.fname='DOM-REPLACE-TEXT-NODE';
return FUNC;
})();
l122;
var l189=internals.make_lisp_string('parentNode');
var l190=internals.make_lisp_string('removeChild');
var l191=internals.make_lisp_string('bind');
l123.fvalue=(function(){var FUNC=(function JSCL_USER_DOMREMOVE(values,v308){internals.checkArgs(arguments.length-1,1);
var v309=this;
return (function(){return (function(){var v311=internals.js_to_lisp((function(){var TMP=v308[internals.xstring(l189)];
return TMP===undefined?l4.value:TMP;
})());
return (function(){var F=internals.js_to_lisp(v311[internals.xstring(l190)][internals.xstring(l191)](internals.lisp_to_js(v311),internals.lisp_to_js(v308)));
return (typeof F==='function'?F:F.fvalue)(values);
})();
})();
})();
});
FUNC.fname='DOM-REMOVE';
return FUNC;
})();
l123;
var l192=internals.make_lisp_string('className');
var l193=internals.make_lisp_string(' ');
l124.fvalue=(function(){var FUNC=(function JSCL_USER_DOMADDCLASS(values,v312,v313){internals.checkArgs(arguments.length-1,2);
var v314=this;
return (function(){return (function(v317){return (function(){var v318=v312;
var v319=l192;
return (function(){var FUNC=(function JSCL_USER_NIL(values,v321){switch(arguments.length-1){case 0:v321=l4.value;
;
default:break;
}var v320=l4.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v320=new internals.Cons(arguments[I+1],v320);
var v322=this;
return (function(){var OBJ=v318;
var TMP=(OBJ[internals.xstring(v319)]=internals.lisp_to_js(v321));
return TMP===undefined?l4.value:TMP;
})();
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=v317!==l4.value?l25.fvalue(values,v317,l193,v313):v313;
if (typeof VS==='object'&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
})((function(v316){return v316!==l4.value?v316:l17;
})(internals.js_to_lisp((function(){var TMP=v312[internals.xstring(l192)];
return TMP===undefined?l4.value:TMP;
})())));
})();
});
FUNC.fname='DOM-ADD-CLASS';
return FUNC;
})();
l124;
var l194=internals.QIList(' ',l4);
var l195=internals.make_lisp_string('className');
var l196=internals.intern('TEST','KEYWORD');
l196.value=l196;
var l197=internals.intern('REMOVE','COMMON-LISP');
var l198=internals.make_lisp_string(' ');
var l199=internals.intern('JOIN');
l125.fvalue=(function(){var FUNC=(function JSCL_USER_DOMREMOVECLASS(values,v323,v324){internals.checkArgs(arguments.length-1,2);
var v325=this;
return (function(){return (function(v327){return (function(){var v328=v323;
var v329=l195;
return (function(){var FUNC=(function JSCL_USER_NIL(values,v331){switch(arguments.length-1){case 0:v331=l4.value;
;
default:break;
}var v330=l4.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v330=new internals.Cons(arguments[I+1],v330);
var v332=this;
return (function(){var OBJ=v328;
var TMP=(OBJ[internals.xstring(v329)]=internals.lisp_to_js(v331));
return TMP===undefined?l4.value:TMP;
})();
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=l199.fvalue(values,l197.fvalue(internals.pv,v324,v327,l196.value,internals.symbolFunction(l19)),l198);
if (typeof VS==='object'&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
})(l15.fvalue(internals.pv,l194,internals.js_to_lisp((function(){var TMP=v323[internals.xstring(l195)];
return TMP===undefined?l4.value:TMP;
})())));
})();
});
FUNC.fname='DOM-REMOVE-CLASS';
return FUNC;
})();
l125;
var l200=internals.QIList(' ',l4);
var l201=internals.make_lisp_string('className');
l126.fvalue=(function(){var FUNC=(function JSCL_USER_DOMHAVECLASSP(values,v333,v334){internals.checkArgs(arguments.length-1,2);
var v335=this;
return (function(){return (function(v337){return l32.fvalue(internals.pv,v334,v337,l196.value,internals.symbolFunction(l19))!==l4.value?l7.value:l4.value;
})(l15.fvalue(internals.pv,l200,internals.js_to_lisp((function(){var TMP=v333[internals.xstring(l201)];
return TMP===undefined?l4.value:TMP;
})())));
})();
});
FUNC.fname='DOM-HAVE-CLASS-P';
return FUNC;
})();
l126;
var l202=internals.make_lisp_string('appendChild');
var l203=internals.make_lisp_string('bind');
l127.fvalue=(function(){var FUNC=(function JSCL_USER_DOMAPPEND(values,v339){internals.checkArgsAtLeast(arguments.length-1,1);
var v338=l4.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v338=new internals.Cons(arguments[I+1],v338);
var v340=this;
return (function(){return l63.fvalue(values,(function JSCL_USER_NIL(values,v342){internals.checkArgs(arguments.length-1,1);
var v343=this;
return l117.fvalue(internals.pv,v342)!==l4.value?(function(){var F=internals.js_to_lisp(v339[internals.xstring(l202)][internals.xstring(l203)](internals.lisp_to_js(v339),internals.lisp_to_js(v342)));
return (typeof F==='function'?F:F.fvalue)(values);
})():l120.fvalue(values,v339,l25.fvalue(internals.pv,l119.fvalue(internals.pv,v339),v342));
}),v338);
})();
});
FUNC.fname='DOM-APPEND';
return FUNC;
})();
l127;
var l204=internals.make_lisp_string('dom-mount: parent must be dom. ~s');
var l205=internals.make_lisp_string('appendChild');
var l206=internals.make_lisp_string('bind');
l128.fvalue=(function(){var FUNC=(function JSCL_USER_DOMMOUNT(values,v345){internals.checkArgsAtLeast(arguments.length-1,1);
var v344=l4.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v344=new internals.Cons(arguments[I+1],v344);
var v346=this;
return (function(){if (l36.fvalue(internals.pv,l117.fvalue(internals.pv,v345))!==l4.value) l41.fvalue(internals.pv,l204,v345);
 else l4.value;
l63.fvalue(internals.pv,(function JSCL_USER_NIL(values,v348){internals.checkArgs(arguments.length-1,1);
var v349=this;
return l117.fvalue(internals.pv,v348)!==l4.value?(function(){var F=internals.js_to_lisp(v345[internals.xstring(l205)][internals.xstring(l206)](internals.lisp_to_js(v345),internals.lisp_to_js(v348)));
return (typeof F==='function'?F:F.fvalue)(values);
})():l120.fvalue(values,v345,l25.fvalue(internals.pv,l119.fvalue(internals.pv,v345),v348));
}),v344);
return v345;
})();
});
FUNC.fname='DOM-MOUNT';
return FUNC;
})();
l128;
var l207=internals.make_lisp_string('innerHTML');
l129.fvalue=(function(){var FUNC=(function JSCL_USER_DOMCLEAR(values,v350){internals.checkArgs(arguments.length-1,1);
var v351=this;
return (function(){return (function(){var v353=v350;
var v354=l207;
return (function(){var FUNC=(function JSCL_USER_NIL(values,v356){switch(arguments.length-1){case 0:v356=l4.value;
;
default:break;
}var v355=l4.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v355=new internals.Cons(arguments[I+1],v355);
var v357=this;
return (function(){var OBJ=v353;
var TMP=(OBJ[internals.xstring(v354)]=internals.lisp_to_js(v356));
return TMP===undefined?l4.value:TMP;
})();
});
var ARGS=[values];
return (function(){var values=internals.mv;
var VS;
VS=l17;
if (typeof VS==='object'&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
})();
});
FUNC.fname='DOM-CLEAR';
return FUNC;
})();
l129;
var l208=internals.make_lisp_string('window');
var l209=internals.make_lisp_string('document');
var l210=internals.make_lisp_string('createElement');
l130.fvalue=(function(){var FUNC=(function JSCL_USER_DOMCREATE(values,v358,v359,v360){internals.checkArgsAtLeast(arguments.length-1,1);
internals.checkArgsAtMost(arguments.length-1,3);
switch(arguments.length-1){case 1:v359=l4.value;
;
case 2:v360=l4.value;
;
default:break;
}var v361=this;
return (function(){return (function(v363){if (v359!==l4.value) l63.fvalue(internals.pv,(function JSCL_USER_NIL(values,v364){internals.checkArgs(arguments.length-1,1);
var v365=this;
return l113.fvalue(values,v363,internals.car(v364),internals.cdr(v364));
}),v359);
 else l4.value;
if (v360!==l4.value) l63.fvalue(internals.pv,(function JSCL_USER_NIL(values,v366){internals.checkArgs(arguments.length-1,1);
var v367=this;
return l116.fvalue(values,v363,internals.car(v366),internals.cdr(v366));
}),v360);
 else l4.value;
return v363;
})(internals.js_to_lisp(internals.symbolValue(l81)[internals.xstring(l208)][internals.xstring(l209)][internals.xstring(l210)](internals.lisp_to_js(v358))));
})();
});
FUNC.fname='DOM-CREATE';
return FUNC;
})();
l130;
var l211=internals.make_lisp_string('input');
l131.fvalue=(function(){var FUNC=(function JSCL_USER_DOMCREATEINPUT(values,v368,v369){internals.checkArgsAtMost(arguments.length-1,2);
switch(arguments.length-1){case 0:v368=l4.value;
;
case 1:v369=l4.value;
;
default:break;
}var v370=this;
return (function(){return l130.fvalue(values,l211,v368,v369);
})();
});
FUNC.fname='DOM-CREATE-INPUT';
return FUNC;
})();
l131;
var l212=internals.QIList(internals.QIList(internals.make_lisp_string('type'),internals.make_lisp_string('text')),l4);
l132.fvalue=(function(){var FUNC=(function JSCL_USER_DOMCREATETEXT(values,v372,v373){internals.checkArgsAtMost(arguments.length-1,2);
switch(arguments.length-1){case 0:v372=l4.value;
;
case 1:v373=l4.value;
;
default:break;
}var v374=this;
return (function(){return l131.fvalue(values,l64.fvalue(internals.pv,v372,l212),v373);
})();
});
FUNC.fname='DOM-CREATE-TEXT';
return FUNC;
})();
l132;
var l213=internals.QIList(internals.make_lisp_string('type'),internals.make_lisp_string('button'));
var l214=internals.make_lisp_string('value');
l133.fvalue=(function(){var FUNC=(function JSCL_USER_DOMCREATEBUTTON(values,v376,v377,v378){internals.checkArgsAtLeast(arguments.length-1,1);
internals.checkArgsAtMost(arguments.length-1,3);
switch(arguments.length-1){case 1:v377=l4.value;
;
case 2:v378=l4.value;
;
default:break;
}var v379=this;
return (function(){return l131.fvalue(values,l64.fvalue(internals.pv,v377,l75.fvalue(internals.pv,l213,new internals.Cons(l214,v376))),v378);
})();
});
FUNC.fname='DOM-CREATE-BUTTON';
return FUNC;
})();
l133;
var l215=internals.QIList(internals.make_lisp_string('type'),internals.make_lisp_string('checkbox'));
l134.fvalue=(function(){var FUNC=(function JSCL_USER_DOMCREATECHECKBOX(values,v381,v382){internals.checkArgsAtMost(arguments.length-1,2);
switch(arguments.length-1){case 0:v381=l4.value;
;
case 1:v382=l4.value;
;
default:break;
}var v383=this;
return (function(){return l131.fvalue(values,new internals.Cons(l215,v381),v382);
})();
});
FUNC.fname='DOM-CREATE-CHECKBOX';
return FUNC;
})();
l134;
var l216=internals.make_lisp_string('parentNode');
l135.fvalue=(function(){var FUNC=(function JSCL_USER_DOMPARENTNODE(values,v385){internals.checkArgs(arguments.length-1,1);
var v386=this;
return (function(){return internals.js_to_lisp((function(){var TMP=v385[internals.xstring(l216)];
return TMP===undefined?l4.value:TMP;
})());
})();
});
FUNC.fname='DOM-PARENT-NODE';
return FUNC;
})();
l135;
var l217=internals.make_lisp_string('nodeName');
l136.fvalue=(function(){var FUNC=(function JSCL_USER_DOMELEMENTNODENAME(values,v388){internals.checkArgs(arguments.length-1,1);
var v389=this;
return (function(){return internals.js_to_lisp((function(){var TMP=v388[internals.xstring(l217)];
return TMP===undefined?l4.value:TMP;
})());
})();
});
FUNC.fname='DOM-ELEMENT-NODE-NAME';
return FUNC;
})();
l136;
var l218=internals.intern('DOM-ELEMENT-HAS-CHILD-P');
var l219=internals.make_lisp_string('hasChildNodes');
var l220=internals.make_lisp_string('bind');
l218.fvalue=(function(){var FUNC=(function JSCL_USER_DOMELEMENTHASCHILDP(values,v391){internals.checkArgs(arguments.length-1,1);
var v392=this;
return (function(){return (function(){var F=internals.js_to_lisp(v391[internals.xstring(l219)][internals.xstring(l220)](internals.lisp_to_js(v391)));
return (typeof F==='function'?F:F.fvalue)(values);
})();
})();
});
FUNC.fname='DOM-ELEMENT-HAS-CHILD-P';
return FUNC;
})();
l218;
var l221=internals.make_lisp_string('childElementCount');
l138.fvalue=(function(){var FUNC=(function JSCL_USER_DOMELEMENTCHILDCOUNT(values,v394){internals.checkArgs(arguments.length-1,1);
var v395=this;
return (function(){return internals.js_to_lisp((function(){var TMP=v394[internals.xstring(l221)];
return TMP===undefined?l4.value:TMP;
})());
})();
});
FUNC.fname='DOM-ELEMENT-CHILD-COUNT';
return FUNC;
})();
l138;
var l222=internals.make_lisp_string('childElementCount');
var l223=internals.make_lisp_string('childNodes');
l139.fvalue=(function(){var FUNC=(function JSCL_USER_DOMELEMENTCHILDSCOLLECTION(values,v397){internals.checkArgs(arguments.length-1,1);
var v398=this;
return (function(){return (function(v400,v401){return (function(){var x1=v400;
if (typeof x1!='number') throw 'Not a number!';
return x1>0?l7.value:l4.value;
})()!==l4.value?((function(){return (function(v403){return (function(){try{var v404=[];
return (function(){while (l7.value!==l4.value){if ((function(){var x1=v403;
if (typeof x1!='number') throw 'Not a number!';
var x2=v400;
if (typeof x2!='number') throw 'Not a number!';
return x1==x2?l7.value:l4.value;
})()!==l4.value) (function(){throw new internals.BlockNLX(v404,v403,'NIL');
})();
 else l4.value;
(function(){var v405=internals.js_to_lisp((function(){var TMP=v397[internals.xstring(l223)];
if (TMP===undefined) return l4.value;
TMP=TMP[internals.xstring(l13.fvalue(internals.pv,l37.fvalue(internals.pv,v403)))];
return TMP===undefined?l4.value:TMP;
})());
var v406=new internals.Cons(v405,v401);
return v401=v406;
})();
l4.value;
(function(v407){return v403=v407;
})(l37.fvalue(internals.pv,v403));
}return l4.value;
})();
}catch (CF){if (CF instanceof internals.BlockNLX&&CF.id==v404) return CF.values;
 else throw CF;
}})();
})(0);
})(),l21.fvalue(values,v401)):v401;
})(internals.js_to_lisp((function(){var TMP=v397[internals.xstring(l222)];
return TMP===undefined?l4.value:TMP;
})()),l4.value);
})();
});
FUNC.fname='DOM-ELEMENT-CHILDS-COLLECTION';
return FUNC;
})();
l139;
var l224=internals.make_lisp_string('firstElementChild');
l140.fvalue=(function(){var FUNC=(function JSCL_USER_DOMELEMENTFIRSTCHILD(values,v408){internals.checkArgs(arguments.length-1,1);
var v409=this;
return (function(){return internals.js_to_lisp((function(){var TMP=v408[internals.xstring(l224)];
return TMP===undefined?l4.value:TMP;
})());
})();
});
FUNC.fname='DOM-ELEMENT-FIRST-CHILD';
return FUNC;
})();
l140;
var l225=internals.make_lisp_string('lastElementChild');
l141.fvalue=(function(){var FUNC=(function JSCL_USER_DOMELEMENTLASTCHILD(values,v411){internals.checkArgs(arguments.length-1,1);
var v412=this;
return (function(){return internals.js_to_lisp((function(){var TMP=v411[internals.xstring(l225)];
return TMP===undefined?l4.value:TMP;
})());
})();
});
FUNC.fname='DOM-ELEMENT-LAST-CHILD';
return FUNC;
})();
l141;
var l226=internals.make_lisp_string('nextSibling');
l142.fvalue=(function(){var FUNC=(function JSCL_USER_DOMELEMENTNEXTSIBLING(values,v414){internals.checkArgs(arguments.length-1,1);
var v415=this;
return (function(){return internals.js_to_lisp((function(){var TMP=v414[internals.xstring(l226)];
return TMP===undefined?l4.value:TMP;
})());
})();
});
FUNC.fname='DOM-ELEMENT-NEXT-SIBLING';
return FUNC;
})();
l142;
var l227=internals.make_lisp_string('parentNode');
l143.fvalue=(function(){var FUNC=(function JSCL_USER_DOMELEMENTPARENTNODE(values,v417){internals.checkArgs(arguments.length-1,1);
var v418=this;
return (function(){return internals.js_to_lisp((function(){var TMP=v417[internals.xstring(l227)];
return TMP===undefined?l4.value:TMP;
})());
})();
});
FUNC.fname='DOM-ELEMENT-PARENT-NODE';
return FUNC;
})();
l143;
var l228=internals.make_lisp_string('parentNode');
var l229=internals.make_lisp_string('insertBefore');
var l230=internals.make_lisp_string('bind');
l144.fvalue=(function(){var FUNC=(function JSCL_USER_DOMINSERTBEFORE(values,v420,v421){internals.checkArgs(arguments.length-1,2);
var v422=this;
return (function(){return (function(){var F=internals.js_to_lisp(v420[internals.xstring(l228)][internals.xstring(l229)][internals.xstring(l230)](internals.lisp_to_js(l143.fvalue(internals.pv,v420)),internals.lisp_to_js(v421),internals.lisp_to_js(v420)));
return (typeof F==='function'?F:F.fvalue)(values);
})();
})();
});
FUNC.fname='DOM-INSERT-BEFORE';
return FUNC;
})();
l144;
var l231=internals.make_lisp_string('parentNode');
var l232=internals.make_lisp_string('insertBefore');
var l233=internals.make_lisp_string('bind');
l145.fvalue=(function(){var FUNC=(function JSCL_USER_DOMINSERTAFTER(values,v424,v425){internals.checkArgs(arguments.length-1,2);
var v426=this;
return (function(){return (function(){var F=internals.js_to_lisp(v424[internals.xstring(l231)][internals.xstring(l232)][internals.xstring(l233)](internals.lisp_to_js(l143.fvalue(internals.pv,v424)),internals.lisp_to_js(v425),internals.lisp_to_js(l142.fvalue(internals.pv,v424))));
return (typeof F==='function'?F:F.fvalue)(values);
})();
})();
});
FUNC.fname='DOM-INSERT-AFTER';
return FUNC;
})();
l145;
var l234=internals.intern('NEW-ELEMENT');
var l235=internals.make_lisp_string('insertBefore');
var l236=internals.make_lisp_string('bind');
l146.fvalue=(function(){var FUNC=(function JSCL_USER_DOMINSERTTOP(values,v428,v429){internals.checkArgs(arguments.length-1,2);
var v430=this;
return (function(){return (function(){var F=internals.js_to_lisp(v428[internals.xstring(l235)][internals.xstring(l236)](internals.lisp_to_js(v428),internals.lisp_to_js(internals.symbolValue(l234)),internals.lisp_to_js(l140.fvalue(internals.pv,v428))));
return (typeof F==='function'?F:F.fvalue)(values);
})();
})();
});
FUNC.fname='DOM-INSERT-TOP';
return FUNC;
})();
l146;
var l237=internals.make_lisp_string('appendChild');
var l238=internals.make_lisp_string('bind');
l147.fvalue=(function(){var FUNC=(function JSCL_USER_DOMINSERT(values,v432,v433){internals.checkArgs(arguments.length-1,2);
var v434=this;
return (function(){return (function(){var F=internals.js_to_lisp(v432[internals.xstring(l237)][internals.xstring(l238)](internals.lisp_to_js(v432),internals.lisp_to_js(v433)));
return (typeof F==='function'?F:F.fvalue)(values);
})();
})();
});
FUNC.fname='DOM-INSERT';
return FUNC;
})();
l147;
var l239=internals.intern('RES-ALLOC');
var l240=internals.intern('RES-REFER');
var l241=internals.intern('RES-DROP');
var l242=internals.intern('RES-SCRIPT-LOAD');
var l243=internals.intern('RES-CSS-LOAD');
var l244=internals.intern('RES-IMAGE-LOAD');
var l245=internals.intern('RES-MOUNT');
var l246=internals.intern('RES-REMOVE');
var l247=internals.QIList(l239,l240,l241,l242,l243,l244,l245,l246,l4);
l6.fvalue(internals.pv,l247);
var l248=internals.intern('*RESOURCES*');
var l249=internals.intern('MAKE-HASH-TABLE','COMMON-LISP');
l248.value=l249.fvalue(internals.pv,l196.value,internals.symbolFunction(l19));
l248;
var l250=internals.intern('ENSURE-HT-KEY');
var l251=internals.intern('INTEGERP','COMMON-LISP');
l250.fvalue=(function(){var FUNC=(function JSCL_USER_ENSUREHTKEY(values,v436){internals.checkArgs(arguments.length-1,1);
var v437=this;
return (function(){return (function(){var X=v436;
return typeof X==='object'&&'length' in X&&X.stringp==1?l7.value:l4.value;
})()!==l4.value?v436:l251.fvalue(internals.pv,v436)!==l4.value?l13.fvalue(values,v436):v436;
})();
});
FUNC.fname='ENSURE-HT-KEY';
return FUNC;
})();
l250;
var l252=internals.intern('SETHASH');
l239.fvalue=(function(){var FUNC=(function JSCL_USER_RESALLOC(values,v439,v440){internals.checkArgs(arguments.length-1,2);
var v441=this;
return (function(){return (function(){var v443=l250.fvalue(internals.pv,v439);
var v444=internals.symbolValue(l248);
var v445=l4.value;
return (function(){var FUNC=(function JSCL_USER_NIL(values,v447){switch(arguments.length-1){case 0:v447=l4.value;
;
default:break;
}var v446=l4.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v446=new internals.Cons(arguments[I+1],v446);
var v448=this;
return l252.fvalue(internals.pv,v447,v443,v444),v447;
});
var ARGS=[values];
return (function(){var values=internals.mv;
var VS;
VS=v440;
if (typeof VS==='object'&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
})();
});
FUNC.fname='RES-ALLOC';
return FUNC;
})();
l239;
var l253=internals.intern('GETHASH','COMMON-LISP');
l240.fvalue=(function(){var FUNC=(function JSCL_USER_RESREFER(values,v449){internals.checkArgs(arguments.length-1,1);
var v450=this;
return (function(){return l253.fvalue(values,l250.fvalue(internals.pv,v449),internals.symbolValue(l248));
})();
});
FUNC.fname='RES-REFER';
return FUNC;
})();
l240;
var l254=internals.make_lisp_string('parentNode');
var l255=internals.make_lisp_string('remove');
var l256=internals.make_lisp_string('bind');
var l257=internals.intern('REMHASH','COMMON-LISP');
l241.fvalue=(function(){var FUNC=(function JSCL_USER_RESDROP(values,v452){internals.checkArgs(arguments.length-1,1);
var v453=this;
return (function(){return (function(){var v455=l253.fvalue(internals.pv,l250.fvalue(internals.pv,v452),internals.symbolValue(l248));
return v455!==l4.value?((l117.fvalue(internals.pv,v455)!==l4.value?internals.js_to_lisp((function(){var TMP=v455[internals.xstring(l254)];
return TMP===undefined?l4.value:TMP;
})())===null?l7.value:l4.value:l4.value)!==l4.value?(function(){var F=internals.js_to_lisp(v455[internals.xstring(l255)][internals.xstring(l256)](internals.lisp_to_js(v455)));
return (typeof F==='function'?F:F.fvalue)(internals.pv);
})():l4.value,(function(){var v456=l250.fvalue(internals.pv,v452);
var v457=internals.symbolValue(l248);
var v458=l4.value;
return (function(){var FUNC=(function JSCL_USER_NIL(values,v460){switch(arguments.length-1){case 0:v460=l4.value;
;
default:break;
}var v459=l4.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v459=new internals.Cons(arguments[I+1],v459);
var v461=this;
return l252.fvalue(internals.pv,v460,v456,v457),v460;
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=l4.value;
if (typeof VS==='object'&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})(),l257.fvalue(internals.pv,l250.fvalue(internals.pv,v452),internals.symbolValue(l248)),(function(){return (function(){var FUNC=(function JSCL_USER_NIL(values,v463){switch(arguments.length-1){case 0:v463=l4.value;
;
default:break;
}var v462=l4.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v462=new internals.Cons(arguments[I+1],v462);
var v464=this;
return v455=v463;
});
var ARGS=[values];
return (function(){var values=internals.mv;
var VS;
VS=l4.value;
if (typeof VS==='object'&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})()):l4.value;
})();
})();
});
FUNC.fname='RES-DROP';
return FUNC;
})();
l241;
var l258=internals.intern('WHERE','KEYWORD');
l258.value=l258;
var l259=internals.intern('ONLOAD','KEYWORD');
l259.value=l259;
var l260=internals.intern('ONERROR','KEYWORD');
l260.value=l260;
var l261=internals.make_lisp_string('script');
var l262=internals.make_lisp_string('type');
var l263=internals.make_lisp_string('text/javascript');
var l264=internals.make_lisp_string('onload');
var l265=internals.make_lisp_string('onerror');
var l266=internals.make_lisp_string('src');
l242.fvalue=(function(){var FUNC=(function JSCL_USER_RESSCRIPTLOAD(values,v465,v466){internals.checkArgsAtLeast(arguments.length-1,2);
var v467;
var v468;
var v469;
var I;
for (I=2;I<arguments.length-1;I+=2)if (arguments[I+1]===l258.value) {v467=arguments[I+1+1];
break;
}if (I==arguments.length-1) v467=l106.fvalue(internals.pv);
for (I=2;I<arguments.length-1;I+=2)if (arguments[I+1]===l259.value) {v468=arguments[I+1+1];
break;
}if (I==arguments.length-1) v468=l4.value;
for (I=2;I<arguments.length-1;I+=2)if (arguments[I+1]===l260.value) {v469=arguments[I+1+1];
break;
}if (I==arguments.length-1) v469=l4.value;
var START=2;
if ((arguments.length-1-START)%2==1) throw 'Odd number of keyword arguments.';
for (I=START;I<arguments.length-1;I+=2)if (arguments[I+1]!==l258.value&&arguments[I+1]!==l259.value&&arguments[I+1]!==l260.value) throw 'Unknown keyword argument '+arguments[I+1]['name'];
var v470=this;
return (function(){return (function(){var v472=l130.fvalue(internals.pv,l261,l75.fvalue(internals.pv,new internals.Cons(l262,l263)));
l127.fvalue(internals.pv,v467,v472);
l116.fvalue(internals.pv,v472,l264,(function JSCL_USER_NIL(values,v473){internals.checkArgs(arguments.length-1,1);
var v474=this;
l239.fvalue(internals.pv,v465,v472);
return v468!==l4.value?(function(){var F=v468;
return (typeof F==='function'?F:F.fvalue)(values);
})():l4.value;
}));
if (v469!==l4.value) l116.fvalue(internals.pv,v472,l265,v469);
 else l4.value;
(function(){var v475=v472;
var v476=l266;
return (function(){var FUNC=(function JSCL_USER_NIL(values,v478){switch(arguments.length-1){case 0:v478=l4.value;
;
default:break;
}var v477=l4.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v477=new internals.Cons(arguments[I+1],v477);
var v479=this;
return (function(){var OBJ=v475;
var TMP=(OBJ[internals.xstring(v476)]=internals.lisp_to_js(v478));
return TMP===undefined?l4.value:TMP;
})();
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=v466;
if (typeof VS==='object'&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
return values();
})();
})();
});
FUNC.fname='RES-SCRIPT-LOAD';
return FUNC;
})();
l242;
var l267=internals.make_lisp_string('link');
var l268=internals.make_lisp_string('rel');
var l269=internals.make_lisp_string('stylesheet');
var l270=internals.make_lisp_string('type');
var l271=internals.make_lisp_string('text/css');
var l272=internals.make_lisp_string('onload');
var l273=internals.make_lisp_string('onerror');
var l274=internals.make_lisp_string('href');
l243.fvalue=(function(){var FUNC=(function JSCL_USER_RESCSSLOAD(values,v480,v481){internals.checkArgsAtLeast(arguments.length-1,2);
var v482;
var v483;
var v484;
var I;
for (I=2;I<arguments.length-1;I+=2)if (arguments[I+1]===l258.value) {v482=arguments[I+1+1];
break;
}if (I==arguments.length-1) v482=l106.fvalue(internals.pv);
for (I=2;I<arguments.length-1;I+=2)if (arguments[I+1]===l259.value) {v483=arguments[I+1+1];
break;
}if (I==arguments.length-1) v483=l4.value;
for (I=2;I<arguments.length-1;I+=2)if (arguments[I+1]===l260.value) {v484=arguments[I+1+1];
break;
}if (I==arguments.length-1) v484=l4.value;
var START=2;
if ((arguments.length-1-START)%2==1) throw 'Odd number of keyword arguments.';
for (I=START;I<arguments.length-1;I+=2)if (arguments[I+1]!==l258.value&&arguments[I+1]!==l259.value&&arguments[I+1]!==l260.value) throw 'Unknown keyword argument '+arguments[I+1]['name'];
var v485=this;
return (function(){(function(){var v487=l130.fvalue(internals.pv,l267,l75.fvalue(internals.pv,new internals.Cons(l268,l269),new internals.Cons(l270,l271)));
l127.fvalue(internals.pv,v482,v487);
l116.fvalue(internals.pv,v487,l272,(function JSCL_USER_NIL(values,v488){internals.checkArgs(arguments.length-1,1);
var v489=this;
l239.fvalue(internals.pv,v480,v487);
return v483!==l4.value?(function(){var F=v483;
return (typeof F==='function'?F:F.fvalue)(values);
})():l4.value;
}));
if (v484!==l4.value) l116.fvalue(internals.pv,v487,l273,v484);
 else l4.value;
return (function(){var v490=v487;
var v491=l274;
return (function(){var FUNC=(function JSCL_USER_NIL(values,v493){switch(arguments.length-1){case 0:v493=l4.value;
;
default:break;
}var v492=l4.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v492=new internals.Cons(arguments[I+1],v492);
var v494=this;
return (function(){var OBJ=v490;
var TMP=(OBJ[internals.xstring(v491)]=internals.lisp_to_js(v493));
return TMP===undefined?l4.value:TMP;
})();
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=v481;
if (typeof VS==='object'&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
})();
return values();
})();
});
FUNC.fname='RES-CSS-LOAD';
return FUNC;
})();
l243;
var l275=internals.intern('GET-ELT-FROM-EVENT');
var l276=internals.make_lisp_string('path');
l275.fvalue=(function(){var FUNC=(function JSCL_USER_GETELTFROMEVENT(values,v495,v496,v497){internals.checkArgsAtLeast(arguments.length-1,1);
internals.checkArgsAtMost(arguments.length-1,3);
switch(arguments.length-1){case 1:v496=l276;
;
case 2:v497=0;
;
default:break;
}var v498=this;
return (function(){return l102.fvalue(values,internals.js_to_lisp((function(){var TMP=v495[internals.xstring(v496)];
return TMP===undefined?l4.value:TMP;
})()),v497);
})();
});
FUNC.fname='GET-ELT-FROM-EVENT';
return FUNC;
})();
l275;
var l277=internals.intern('HEIGHT','KEYWORD');
l277.value=l277;
var l278=internals.intern('WIDTH','KEYWORD');
l278.value=l278;
var l279=internals.make_lisp_string('resource');
var l280=internals.make_lisp_string('image');
var l281=internals.make_lisp_string('img');
var l282=internals.make_lisp_string('id');
var l283=internals.make_lisp_string('height');
var l284=internals.make_lisp_string('width');
var l285=internals.make_lisp_string('onload');
var l286=internals.make_lisp_string('onerror');
var l287=internals.make_lisp_string('src');
l244.fvalue=(function(){var FUNC=(function JSCL_USER_RESIMAGELOAD(values,v500,v501){internals.checkArgsAtLeast(arguments.length-1,2);
var v502;
var v503;
var v504;
var v505;
var I;
for (I=2;I<arguments.length-1;I+=2)if (arguments[I+1]===l277.value) {v502=arguments[I+1+1];
break;
}if (I==arguments.length-1) v502=l4.value;
for (I=2;I<arguments.length-1;I+=2)if (arguments[I+1]===l278.value) {v503=arguments[I+1+1];
break;
}if (I==arguments.length-1) v503=l4.value;
for (I=2;I<arguments.length-1;I+=2)if (arguments[I+1]===l259.value) {v504=arguments[I+1+1];
break;
}if (I==arguments.length-1) v504=l4.value;
for (I=2;I<arguments.length-1;I+=2)if (arguments[I+1]===l260.value) {v505=arguments[I+1+1];
break;
}if (I==arguments.length-1) v505=l4.value;
var START=2;
if ((arguments.length-1-START)%2==1) throw 'Odd number of keyword arguments.';
for (I=START;I<arguments.length-1;I+=2)if (arguments[I+1]!==l277.value&&arguments[I+1]!==l278.value&&arguments[I+1]!==l259.value&&arguments[I+1]!==l260.value) throw 'Unknown keyword argument '+arguments[I+1]['name'];
var v506=this;
return (function(){return (function(){var v508=l8.fvalue(internals.pv,l279,l280);
var v509=l130.fvalue(internals.pv,l281,l75.fvalue(internals.pv,new internals.Cons(l282,v508)));
if (v502!==l4.value) (function(){var v510=v509;
var v511=l283;
return (function(){var FUNC=(function JSCL_USER_NIL(values,v513){switch(arguments.length-1){case 0:v513=l4.value;
;
default:break;
}var v512=l4.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v512=new internals.Cons(arguments[I+1],v512);
var v514=this;
return (function(){var OBJ=v510;
var TMP=(OBJ[internals.xstring(v511)]=internals.lisp_to_js(v513));
return TMP===undefined?l4.value:TMP;
})();
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=v502;
if (typeof VS==='object'&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
 else l4.value;
if (v503!==l4.value) (function(){var v515=v509;
var v516=l284;
return (function(){var FUNC=(function JSCL_USER_NIL(values,v518){switch(arguments.length-1){case 0:v518=l4.value;
;
default:break;
}var v517=l4.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v517=new internals.Cons(arguments[I+1],v517);
var v519=this;
return (function(){var OBJ=v515;
var TMP=(OBJ[internals.xstring(v516)]=internals.lisp_to_js(v518));
return TMP===undefined?l4.value:TMP;
})();
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=v503;
if (typeof VS==='object'&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
 else l4.value;
l116.fvalue(internals.pv,v509,l285,(function JSCL_USER_NIL(values,v520){internals.checkArgs(arguments.length-1,1);
var v521=this;
l239.fvalue(internals.pv,v500,v509);
return v504!==l4.value?(function(){var F=v504;
return (typeof F==='function'?F:F.fvalue)(values);
})():l4.value;
}));
if (v505!==l4.value) l116.fvalue(internals.pv,v509,l286,v505);
 else l4.value;
(function(){var v522=v509;
var v523=l287;
return (function(){var FUNC=(function JSCL_USER_NIL(values,v525){switch(arguments.length-1){case 0:v525=l4.value;
;
default:break;
}var v524=l4.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v524=new internals.Cons(arguments[I+1],v524);
var v526=this;
return (function(){var OBJ=v522;
var TMP=(OBJ[internals.xstring(v523)]=internals.lisp_to_js(v525));
return TMP===undefined?l4.value:TMP;
})();
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=v501;
if (typeof VS==='object'&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
return values();
})();
})();
});
FUNC.fname='RES-IMAGE-LOAD';
return FUNC;
})();
l244;
l245.fvalue=(function(){var FUNC=(function JSCL_USER_RESMOUNT(values,v528,v529){internals.checkArgsAtLeast(arguments.length-1,2);
var v527=l4.value;
var I;
for (I=arguments.length-1-1;I>=2;I--)v527=new internals.Cons(arguments[I+1],v527);
var v530=this;
return (function(){return (function(){var F=internals.symbolFunction(l128);
var ARGS=[values];
var TAIL=l64.fvalue(internals.pv,l75.fvalue(internals.pv,v528),l75.fvalue(internals.pv,l240.fvalue(internals.pv,v529)),v527);
while (TAIL!=l4.value){ARGS.push(TAIL.car);
TAIL=TAIL.cdr;
}return (typeof F==='function'?F:F.fvalue).apply(this,ARGS);
})();
})();
});
FUNC.fname='RES-MOUNT';
return FUNC;
})();
l245;
l246.fvalue=(function(){var FUNC=(function JSCL_USER_RESREMOVE(values,v532,v533,v534,v535,v536,v537){internals.checkArgs(arguments.length-1,6);
var v538=this;
return (function(){return l4.value;
})();
});
FUNC.fname='RES-REMOVE';
return FUNC;
})();
l246;
var l288=internals.intern('LOAD','COMMON-LISP');
var l289=internals.intern('XHR-RECEIVE');
var l290=internals.QIList(l288,l289,l4);
l6.fvalue(internals.pv,l290);
var l291=internals.make_lisp_string('window');
var l292=internals.make_lisp_string('XMLHttpRequest');
var l293=internals.make_lisp_string('opNew');
var l294=internals.make_lisp_string('GET');
var l295=internals.make_lisp_string('open');
var l296=internals.make_lisp_string('bind');
var l297=internals.make_lisp_string('Cache-Control');
var l298=internals.make_lisp_string('no-cache');
var l299=internals.make_lisp_string('setRequestHeader');
var l300=internals.make_lisp_string('bind');
var l301=internals.make_lisp_string('Cache-Control');
var l302=internals.make_lisp_string('no-store');
var l303=internals.make_lisp_string('setRequestHeader');
var l304=internals.make_lisp_string('bind');
var l305=internals.make_lisp_string('onreadystatechange');
var l306=internals.make_lisp_string('readyState');
var l307=internals.make_lisp_string('status');
var l308=internals.make_lisp_string('responseText');
var l309=internals.make_lisp_string('status');
var l310=internals.make_lisp_string('n');
var l311=internals.make_lisp_string('status');
var l312=internals.make_lisp_string(': Error load ');
var l313=internals.intern('NAME');
var l314=internals.make_lisp_string(' - ');
var l315=internals.make_lisp_string('statusText');
var l316=internals.make_lisp_string('console');
var l317=internals.make_lisp_string('log');
var l318=internals.make_lisp_string('reqXHRsendNull');
l289.fvalue=(function(){var FUNC=(function JSCL_USER_XHRRECEIVE(values,v540,v541,v542){internals.checkArgsAtLeast(arguments.length-1,2);
internals.checkArgsAtMost(arguments.length-1,3);
switch(arguments.length-1){case 2:v542=l4.value;
;
default:break;
}var v543=this;
return (function(){return (function(){var v545=internals.js_to_lisp(internals.symbolValue(l81)[internals.xstring(l293)](internals.lisp_to_js(internals.js_to_lisp((function(){var TMP=internals.symbolValue(l81)[internals.xstring(l291)];
return TMP===undefined?l4.value:TMP;
})())),internals.lisp_to_js(l292)));
(function(){var F=internals.js_to_lisp(v545[internals.xstring(l295)][internals.xstring(l296)](internals.lisp_to_js(v545),internals.lisp_to_js(l294),internals.lisp_to_js(v540),internals.lisp_to_js(l7.value)));
return (typeof F==='function'?F:F.fvalue)(internals.pv);
})();
(function(){var F=internals.js_to_lisp(v545[internals.xstring(l299)][internals.xstring(l300)](internals.lisp_to_js(v545),internals.lisp_to_js(l297),internals.lisp_to_js(l298)));
return (typeof F==='function'?F:F.fvalue)(internals.pv);
})();
(function(){var F=internals.js_to_lisp(v545[internals.xstring(l303)][internals.xstring(l304)](internals.lisp_to_js(v545),internals.lisp_to_js(l301),internals.lisp_to_js(l302)));
return (typeof F==='function'?F:F.fvalue)(internals.pv);
})();
(function(){var v546=v545;
var v547=l305;
return (function(){var FUNC=(function JSCL_USER_NIL(values,v549){switch(arguments.length-1){case 0:v549=l4.value;
;
default:break;
}var v548=l4.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v548=new internals.Cons(arguments[I+1],v548);
var v550=this;
return (function(){var OBJ=v546;
var TMP=(OBJ[internals.xstring(v547)]=internals.lisp_to_js(v549));
return TMP===undefined?l4.value:TMP;
})();
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=(function JSCL_USER_NIL(values,v551){internals.checkArgs(arguments.length-1,1);
var v552=this;
return (function(){var x1=internals.js_to_lisp((function(){var TMP=v545[internals.xstring(l306)];
return TMP===undefined?l4.value:TMP;
})());
if (typeof x1!='number') throw 'Not a number!';
return x1==4?l7.value:l4.value;
})()!==l4.value?(function(){var x1=internals.js_to_lisp((function(){var TMP=v545[internals.xstring(l307)];
return TMP===undefined?l4.value:TMP;
})());
if (typeof x1!='number') throw 'Not a number!';
return x1==200?l7.value:l4.value;
})()!==l4.value?(function(){var F=v541;
return (typeof F==='function'?F:F.fvalue)(values,internals.js_to_lisp((function(){var TMP=v545[internals.xstring(l308)];
return TMP===undefined?l4.value:TMP;
})()));
})():l36.fvalue(internals.pv,l20.fvalue(internals.pv,v542))!==l4.value?(function(){var F=v542;
return (typeof F==='function'?F:F.fvalue)(values,v540,internals.js_to_lisp((function(){var TMP=v545[internals.xstring(l309)];
return TMP===undefined?l4.value:TMP;
})()));
})():internals.js_to_lisp(internals.symbolValue(l81)[internals.xstring(l316)][internals.xstring(l317)](internals.lisp_to_js(l25.fvalue(internals.pv,l310,internals.js_to_lisp((function(){var TMP=v545[internals.xstring(l311)];
return TMP===undefined?l4.value:TMP;
})()),l312,internals.symbolValue(l313),l314,internals.js_to_lisp((function(){var TMP=v545[internals.xstring(l315)];
return TMP===undefined?l4.value:TMP;
})()))))):l4.value;
});
if (typeof VS==='object'&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
return internals.js_to_lisp(internals.symbolValue(l81)[internals.xstring(l318)](internals.lisp_to_js(v545)));
})();
})();
});
FUNC.fname='XHR-RECEIVE';
return FUNC;
})();
l289;
var l319=internals.intern('EVAL-FORM');
var l320=internals.make_lisp_string('Catch js error: ~s~%');
var l321=internals.make_lisp_string('message');
var l322=internals.make_lisp_string('Finalyze~%');
var l323=internals.intern('*HANDLER-BINDINGS*');
var l324=internals.intern('WARNING','COMMON-LISP');
var l325=internals.make_lisp_string('message');
var l326=internals.intern('%ERROR');
var l327=internals.make_lisp_string('(');
var l328=internals.make_lisp_string(')');
var l329=internals.intern('READ-FROM-STRING','COMMON-LISP');
var l330=internals.intern('EVAL-INTERACTIVE');
var l331=internals.make_lisp_string('~a ~%');
var l332=internals.make_lisp_string('Warning: ~s~%');
var l333=internals.intern('!CONDITION-ARGS');
var l334=internals.make_lisp_string('Error: ~s~%');
l319.fvalue=(function(){var FUNC=(function JSCL_USER_EVALFORM(values,v553){internals.checkArgs(arguments.length-1,1);
var v554=this;
return (function(){return (function(){try{return (function(){try{var v558=[];
return (function(v559){return (function(){var v560=1;
var v561=[];
TBLOOP:while (true){try{switch(v560){case 1:(function(v562){return internals.bindSpecialBindings([l323],[v562],(function(){(function(){var v563=new internals.Cons(l41,(function JSCL_USER_NIL(values,v564){internals.checkArgs(arguments.length-1,1);
var v565=this;
v559=v564;
return (function(){throw new internals.TagNLX(v561,3);
})();
}));
var v566=new internals.Cons(v563,internals.symbolValue(l323));
return l323.value=v566;
})();
(function(){var v567=new internals.Cons(l324,(function JSCL_USER_NIL(values,v568){internals.checkArgs(arguments.length-1,1);
var v569=this;
v559=v568;
return (function(){throw new internals.TagNLX(v561,2);
})();
}));
var v570=new internals.Cons(v567,internals.symbolValue(l323));
return l323.value=v570;
})();
return (function(){try{return (function(){throw new internals.BlockNLX(v558,(function(){var v573=l329.fvalue(internals.pv,l25.fvalue(internals.pv,l327,v553,l328));
var v574=l4.value;
return (function(){return (function(v576,v577){(function(){while (v576!==l4.value){v577=internals.car(v576);
(function(){return (function(){var FUNC=(function JSCL_USER_NIL(values,v579){switch(arguments.length-1){case 0:v579=l4.value;
;
default:break;
}var v578=l4.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v578=new internals.Cons(arguments[I+1],v578);
var v580=this;
return v574=v579;
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=(function(){var FUNC=internals.symbolFunction(l75);
var ARGS=[values];
return (function(){var values=internals.mv;
var VS;
VS=l330.fvalue(values,v577);
if (typeof VS==='object'&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
if (typeof VS==='object'&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
(function(){return (function(v582,v583){(function(){while (v582!==l4.value){v583=internals.car(v582);
l14.fvalue(internals.pv,l7.value,l331,v583);
l4.value;
v582=internals.cdr(v582);
}return l4.value;
})();
return l4.value;
})(v574,l4.value);
})();
l4.value;
v576=internals.cdr(v576);
}return l4.value;
})();
return l4.value;
})(v573,l4.value);
})();
})(),'G2540');
})();
}catch (v571){v571=internals.js_to_lisp(v571);
return (internals.isNLX(v571)?l7.value:l4.value)!==l4.value?(function(){throw v571;
})():l326.fvalue(internals.pv,(function(v572){return v572!==l4.value?v572:v571;
})(internals.js_to_lisp((function(){var TMP=v571[internals.xstring(l325)];
return TMP===undefined?l4.value:TMP;
})())));
}})();
}));
})(internals.symbolValue(l323));
case 2:(function(){throw new internals.BlockNLX(v558,(function(v584){return l14.fvalue(internals.pv,l7.value,l332,l333.fvalue(internals.pv,v584));
})(v559),'G2540');
})();
case 3:(function(){throw new internals.BlockNLX(v558,(function(v585){return l14.fvalue(internals.pv,l7.value,l334,l333.fvalue(internals.pv,v585));
})(v559),'G2540');
})();
default:break TBLOOP;
}}catch (JUMP){if (JUMP instanceof internals.TagNLX&&JUMP.id==v561) v560=JUMP.label;
 else throw JUMP;
}}return l4.value;
})();
})(l4.value);
}catch (CF){if (CF instanceof internals.BlockNLX&&CF.id==v558) return CF.values;
 else throw CF;
}})();
}catch (v556){v556=internals.js_to_lisp(v556);
return l14.fvalue(values,l7.value,l320,(function(v557){return v557!==l4.value?v557:v556;
})(internals.js_to_lisp((function(){var TMP=v556[internals.xstring(l321)];
return TMP===undefined?l4.value:TMP;
})())));
}finally{l14.fvalue(internals.pv,l7.value,l322);
}})();
})();
});
FUNC.fname='EVAL-FORM';
return FUNC;
})();
l319;
var l335=internals.intern('SUBSTITUTE','COMMON-LISP');
var l336=internals.make_lisp_string("~%Load: Can't load ~s. Status: ~a~%");
l288.fvalue=(function(){var FUNC=(function JSCL_USER_LOAD(values,v586){internals.checkArgs(arguments.length-1,1);
var v587=this;
return (function(){l289.fvalue(internals.pv,v586,(function JSCL_USER_NIL(values,v589){internals.checkArgs(arguments.length-1,1);
var v590=this;
return l319.fvalue(values,l335.fvalue(internals.pv,' ',internals.char_from_codepoint(13),v589));
}),(function JSCL_USER_NIL(values,v591,v592){internals.checkArgs(arguments.length-1,2);
var v593=this;
return l14.fvalue(values,l7.value,l336,v591,v592);
}));
return values();
})();
});
FUNC.fname='LOAD';
return FUNC;
})();
l288;
var l337=internals.intern('RESOURCE-LOADER');
var l338=internals.QIList(l337,l4);
l6.fvalue(internals.pv,l338);
var l339=internals.intern('SCRIPT','KEYWORD');
l339.value=l339;
var l340=internals.intern('EQL','COMMON-LISP');
var l341=internals.make_lisp_string('script');
var l342=internals.make_lisp_string('type');
var l343=internals.make_lisp_string('text/javascript');
var l344=internals.make_lisp_string('src');
var l345=internals.intern('CSS','KEYWORD');
l345.value=l345;
var l346=internals.make_lisp_string('link');
var l347=internals.make_lisp_string('rel');
var l348=internals.make_lisp_string('stylesheet');
var l349=internals.make_lisp_string('type');
var l350=internals.make_lisp_string('text/css');
var l351=internals.make_lisp_string('href');
var l352=internals.make_lisp_string('Resource loader: what load? ~a~%');
var l353=internals.make_lisp_string('onload');
var l354=internals.make_lisp_string('window');
var l355=internals.make_lisp_string('document');
var l356=internals.make_lisp_string('head');
l337.fvalue=(function(){var FUNC=(function JSCL_USER_RESOURCELOADER(values,v594,v595,v596){internals.checkArgsAtLeast(arguments.length-1,2);
internals.checkArgsAtMost(arguments.length-1,3);
switch(arguments.length-1){case 2:v596=l4.value;
;
default:break;
}var v597=this;
return (function(){return (function(){var v599=l4.value;
var v600=l4.value;
(function(v601){return l340.fvalue(internals.pv,v601,l339)!==l4.value?(l4.value,(function(){return (function(){var FUNC=(function JSCL_USER_NIL(values,v603){switch(arguments.length-1){case 0:v603=l4.value;
;
default:break;
}var v602=l4.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v602=new internals.Cons(arguments[I+1],v602);
var v604=this;
return v599=v603;
});
var ARGS=[values];
return (function(){var values=internals.mv;
var VS;
VS=l130.fvalue(values,l341,l75.fvalue(internals.pv,new internals.Cons(l342,l343),new internals.Cons(l344,v595)));
if (typeof VS==='object'&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})()):l340.fvalue(internals.pv,v601,l345)!==l4.value?(l4.value,(function(){return (function(){var FUNC=(function JSCL_USER_NIL(values,v606){switch(arguments.length-1){case 0:v606=l4.value;
;
default:break;
}var v605=l4.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v605=new internals.Cons(arguments[I+1],v605);
var v607=this;
return v599=v606;
});
var ARGS=[values];
return (function(){var values=internals.mv;
var VS;
VS=l130.fvalue(values,l346,l75.fvalue(internals.pv,new internals.Cons(l347,l348),new internals.Cons(l349,l350),new internals.Cons(l351,v595)));
if (typeof VS==='object'&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})()):(l4.value,l41.fvalue(values,l352,v594));
})(v594);
if (v596!==l4.value) l116.fvalue(internals.pv,v599,l353,v596);
 else l4.value;
return l127.fvalue(values,internals.js_to_lisp((function(){var TMP=internals.symbolValue(l81)[internals.xstring(l354)];
if (TMP===undefined) return l4.value;
TMP=TMP[internals.xstring(l355)];
if (TMP===undefined) return l4.value;
TMP=TMP[internals.xstring(l356)];
return TMP===undefined?l4.value:TMP;
})()),v599);
})();
})();
});
FUNC.fname='RESOURCE-LOADER';
return FUNC;
})();
l337;
})(jscl.internals.pv, jscl.internals);
})( typeof require !== 'undefined'? require('./jscl'): window.jscl )
